import { CatalogueCategorySeed } from './types';
import { AFFECTION_INTIMACY, CLOTHING_APPEARANCE, MANUAL_MASTURBATION, ORAL } from './soft';
import { PENETRATION, TOYS, ORGASM_CONTROL, BODY_FETISHES } from './sexual';
import { GROUPS, ROLEPLAY, EXHIBITIONISM } from './social';
import { POWER, RESTRAINT, PSYCHOLOGICAL, SENSATION } from './bdsm';
import { FLUIDS, EDGE } from './intense';

export const CATALOGUE_V3_CONTENT: readonly CatalogueCategorySeed[] = [
  AFFECTION_INTIMACY,
  CLOTHING_APPEARANCE,
  MANUAL_MASTURBATION,
  ORAL,
  PENETRATION,
  TOYS,
  ORGASM_CONTROL,
  BODY_FETISHES,
  GROUPS,
  ROLEPLAY,
  EXHIBITIONISM,
  POWER,
  RESTRAINT,
  PSYCHOLOGICAL,
  SENSATION,
  FLUIDS,
  EDGE,
];
