import { CatalogueCategorySeed } from './types';

export const FLUIDS: CatalogueCategorySeed = {
  id: "fluids",
  en: "Fluids & bodily play",
  es: "Fluidos y prácticas corporales",
  descriptionEn: "Consensual preferences involving saliva, sexual fluids and other bodily-fluid play.",
  descriptionEs: "Preferencias consensuadas relacionadas con saliva, fluidos sexuales y otros juegos corporales.",
  order: 15,
  practices: [
    { id: "spitting-on-body", en: "Spitting on the body", es: "Escupir sobre el cuerpo", kind: 'directed' },
    { id: "spitting-in-mouth", en: "Spitting in the mouth", es: "Escupir en la boca", kind: 'directed' },
    { id: "saliva-sharing", en: "Saliva sharing", es: "Compartir saliva", kind: 'mutual' },
    { id: "drooling", en: "Drooling", es: "Babear", kind: 'directed' },
    { id: "semen-on-body", en: "Semen on body", es: "Semen sobre el cuerpo", kind: 'directed' },
    { id: "semen-on-face", en: "Semen on face", es: "Semen en la cara", kind: 'directed' },
    { id: "semen-on-breasts", en: "Semen on breasts", es: "Semen sobre el pecho", kind: 'directed' },
    { id: "semen-on-buttocks", en: "Semen on buttocks", es: "Semen sobre los glúteos", kind: 'directed' },
    { id: "semen-in-mouth", en: "Semen in mouth", es: "Semen en la boca", kind: 'directed' },
    { id: "swallowing", en: "Swallowing semen", es: "Tragar semen", kind: 'directed' },
    { id: "snowballing", en: "Snowballing", es: "Snowballing", kind: 'mutual' },
    { id: "creampie", en: "Internal ejaculation", es: "Eyaculación interna", kind: 'directed' },
    { id: "creampie-cleanup", en: "Creampie cleanup", es: "Limpieza de creampie", kind: 'directed' },
    { id: "female-ejaculation", en: "Female ejaculation / squirting", es: "Eyaculación femenina / squirting", kind: 'directed', counterpartScoped: true, anatomySex: 'female' },
    { id: "squirting-on-partner", en: "Squirting on a partner", es: "Squirting sobre la pareja", kind: 'directed', counterpartScoped: true, anatomySex: 'female' },
    { id: "urine-play", en: "Urine play", es: "Juego con orina", kind: 'directed' },
    { id: "urinating-on-partner", en: "Urinating on a partner", es: "Orinar sobre la pareja", kind: 'directed' },
    { id: "being-urinated-on", en: "Being urinated on", es: "Que orinen sobre mí", kind: 'directed' },
    { id: "urine-drinking", en: "Urine drinking", es: "Beber orina", kind: 'directed' },
    { id: "sweat-play", en: "Sweat play", es: "Juego con sudor", kind: 'mutual' },
    { id: "sweat-licking", en: "Licking sweat", es: "Lamer sudor", kind: 'directed' },
    { id: "food-body-play", en: "Food on the body", es: "Comida sobre el cuerpo", kind: 'directed' },
    { id: "oil-body-play", en: "Body oil play", es: "Juego con aceite corporal", kind: 'directed' },
    { id: "mud-body-play", en: "Mud or messy body play", es: "Juego corporal con barro o sustancias pringosas", kind: 'mutual' },
  ],
};

export const EDGE: CatalogueCategorySeed = {
  id: "edge",
  en: "Intense / edge practices",
  es: "Prácticas intensas / Edge",
  descriptionEn: "Higher-intensity consensual practices that deserve explicit boundaries and additional safety knowledge.",
  descriptionEs: "Prácticas consensuadas de mayor intensidad que requieren límites explícitos y conocimientos de seguridad adicionales.",
  order: 16,
  practices: [
    { id: "breath-play", en: "Breath play", es: "Juego con la respiración", kind: 'directed' },
    { id: "choking-fantasy", en: "Choking fantasy", es: "Fantasía de estrangulación", kind: 'directed' },
    { id: "smothering", en: "Smothering fantasy", es: "Fantasía de asfixia por cobertura", kind: 'directed' },
    { id: "water-bondage-fantasy", en: "Water bondage fantasy", es: "Fantasía de bondage con agua", kind: 'mutual' },
    { id: "needle-play", en: "Needle play", es: "Juego con agujas", kind: 'directed' },
    { id: "piercing-play", en: "Temporary piercing play", es: "Piercing temporal", kind: 'directed' },
    { id: "blood-play", en: "Blood play", es: "Juego con sangre", kind: 'directed' },
    { id: "cutting-play", en: "Cutting play", es: "Juego con cortes", kind: 'directed' },
    { id: "scarification-fantasy", en: "Scarification fantasy", es: "Fantasía de escarificación", kind: 'directed' },
    { id: "branding-fantasy", en: "Branding fantasy", es: "Fantasía de marcado", kind: 'directed' },
    { id: "hot-wax-intense", en: "High-temperature wax play", es: "Juego intenso con cera", kind: 'directed' },
    { id: "fire-play", en: "Fire play", es: "Juego con fuego", kind: 'directed' },
    { id: "electrostimulation-intense", en: "Intense electrostimulation", es: "Electroestimulación intensa", kind: 'directed' },
    { id: "genital-torture", en: "Genital pain play", es: "Juego de dolor genital", kind: 'directed' },
    { id: "cock-and-ball-torture", en: "Cock and ball torture", es: "Cock and ball torture", kind: 'directed' },
    { id: "breast-torture", en: "Breast pain play", es: "Juego de dolor en el pecho", kind: 'directed' },
    { id: "nipple-torture", en: "Intense nipple play", es: "Juego intenso con pezones", kind: 'directed' },
    { id: "heavy-caning", en: "Heavy caning", es: "Caning intenso", kind: 'directed' },
    { id: "heavy-whipping", en: "Heavy whipping", es: "Látigo intenso", kind: 'directed' },
    { id: "suspension-bondage", en: "Suspension bondage", es: "Bondage en suspensión", kind: 'directed' },
    { id: "inversion-bondage", en: "Inverted bondage", es: "Bondage invertido", kind: 'directed' },
    { id: "predicament-bondage", en: "Predicament bondage", es: "Predicament bondage", kind: 'directed' },
    { id: "long-duration-restraint", en: "Long-duration restraint", es: "Restricción de larga duración", kind: 'directed' },
    { id: "vacuum-bed", en: "Vacuum bed", es: "Vacuum bed", kind: 'directed' },
    { id: "vacuum-cube", en: "Vacuum cube", es: "Vacuum cube", kind: 'directed' },
    { id: "sensory-deprivation-intense", en: "Intense sensory deprivation", es: "Privación sensorial intensa", kind: 'directed' },
    { id: "consensual-abduction-scene", en: "Consensual abduction scene", es: "Escena consensuada de abducción", kind: 'mutual' },
    { id: "consensual-non-consent-intense", en: "Intense consensual non-consent scene", es: "Escena intensa de no consentimiento consensuado", kind: 'mutual' },
    { id: "medical-needle-scene", en: "Medical needle scene", es: "Escena médica con agujas", kind: 'mutual' },
    { id: "extreme-humiliation", en: "Extreme consensual humiliation", es: "Humillación consensuada extrema", kind: 'directed' },
  ],
};
