import { CatalogueCategorySeed } from './types';

export const POWER: CatalogueCategorySeed = {
  id: "power",
  en: "Dominance, submission & discipline",
  es: "Dominación, sumisión y disciplina",
  descriptionEn: "Consensual authority, obedience, service, protocol and discipline.",
  descriptionEs: "Autoridad, obediencia, servicio, protocolo y disciplina consensuados.",
  order: 11,
  practices: [
    { id: "domination", en: "Dominance and submission", es: "Dominación y sumisión", kind: 'power' },
    { id: "commands", en: "Giving and following commands", es: "Dar y seguir órdenes", kind: 'power' },
    { id: "obedience", en: "Obedience", es: "Obediencia", kind: 'power' },
    { id: "service", en: "Service", es: "Servicio", kind: 'power' },
    { id: "protocol", en: "Protocol", es: "Protocolo", kind: 'power' },
    { id: "rules", en: "Rules", es: "Reglas", kind: 'power' },
    { id: "discipline", en: "Discipline", es: "Disciplina", kind: 'power' },
    { id: "punishment", en: "Consensual punishment", es: "Castigo consensuado", kind: 'power' },
    { id: "reward-system", en: "Rewards and incentives", es: "Recompensas e incentivos", kind: 'power' },
    { id: "training", en: "Training dynamic", es: "Dinámica de entrenamiento", kind: 'power' },
    { id: "ownership", en: "Ownership dynamic", es: "Dinámica de pertenencia", kind: 'power' },
    { id: "collaring", en: "Collaring", es: "Collaring / poner collar", kind: 'power' },
    { id: "leash-control", en: "Leash control", es: "Control con correa", kind: 'power' },
    { id: "permission-dynamic", en: "Permission-based dynamic", es: "Dinámica basada en permisos", kind: 'power' },
    { id: "chores-service", en: "Chore-based service", es: "Servicio mediante tareas", kind: 'power' },
    { id: "sexual-service", en: "Sexual service", es: "Servicio sexual", kind: 'power' },
    { id: "domestic-service", en: "Domestic service", es: "Servicio doméstico", kind: 'power' },
    { id: "kneeling", en: "Kneeling", es: "Arrodillarse", kind: 'power' },
    { id: "standing-at-attention", en: "Standing at attention", es: "Permanecer firme / en posición", kind: 'power' },
    { id: "inspection", en: "Inspection", es: "Inspección", kind: 'power' },
    { id: "addressing-with-titles", en: "Using titles", es: "Uso de títulos", kind: 'power' },
    { id: "formal-protocol", en: "Formal protocol", es: "Protocolo formal", kind: 'power' },
    { id: "behavior-control", en: "Behavior control", es: "Control del comportamiento", kind: 'power' },
    { id: "clothing-control", en: "Clothing control", es: "Control de la ropa", kind: 'power' },
    { id: "speech-control", en: "Speech control", es: "Control del habla", kind: 'power' },
    { id: "position-control", en: "Position control", es: "Control de posturas", kind: 'power' },
    { id: "orgasm-authority", en: "Orgasm authority", es: "Autoridad sobre el orgasmo", kind: 'power' },
    { id: "financial-control-roleplay", en: "Financial-control roleplay", es: "Roleplay de control financiero", kind: 'power' },
  ],
};

export const RESTRAINT: CatalogueCategorySeed = {
  id: "restraint",
  en: "Bondage & restraint",
  es: "Ataduras y restricción",
  descriptionEn: "Physical restraint, immobilization, sensory restriction and bondage positions.",
  descriptionEs: "Restricción física, inmovilización, limitación sensorial y posiciones de bondage.",
  order: 12,
  practices: [
    { id: "bondage", en: "Bondage", es: "Bondage", kind: 'directed' },
    { id: "rope-bondage", en: "Rope bondage", es: "Bondage con cuerdas", kind: 'directed' },
    { id: "shibari", en: "Shibari", es: "Shibari", kind: 'directed' },
    { id: "handcuffs", en: "Handcuffs", es: "Esposas", kind: 'directed' },
    { id: "wrist-cuffs", en: "Wrist cuffs", es: "Muñequeras", kind: 'directed' },
    { id: "ankle-cuffs", en: "Ankle cuffs", es: "Tobilleras", kind: 'directed' },
    { id: "leather-restraints", en: "Leather restraints", es: "Restricciones de cuero", kind: 'directed' },
    { id: "velcro-restraints", en: "Velcro restraints", es: "Restricciones de velcro", kind: 'directed' },
    { id: "tape-restraint", en: "Tape restraint", es: "Restricción con cinta", kind: 'directed' },
    { id: "chain-restraint", en: "Chain restraint", es: "Restricción con cadenas", kind: 'directed' },
    { id: "bed-restraints", en: "Bed restraints", es: "Restricciones para cama", kind: 'directed' },
    { id: "under-bed-restraints", en: "Under-bed restraints", es: "Restricciones bajo cama", kind: 'directed' },
    { id: "spreader-bar", en: "Spreader bar", es: "Barra separadora", kind: 'directed' },
    { id: "hogtie", en: "Hogtie", es: "Hogtie", kind: 'directed' },
    { id: "frogtie", en: "Frogtie", es: "Frogtie", kind: 'directed' },
    { id: "box-tie", en: "Box tie", es: "Box tie", kind: 'directed' },
    { id: "chest-harness-bondage", en: "Chest harness bondage", es: "Arnés de pecho con cuerdas", kind: 'directed' },
    { id: "full-body-bondage", en: "Full-body bondage", es: "Bondage de cuerpo entero", kind: 'directed' },
    { id: "mummification", en: "Mummification restraint", es: "Mummification / momificación", kind: 'directed' },
    { id: "straightjacket", en: "Straightjacket", es: "Camisa de fuerza", kind: 'directed' },
    { id: "bondage-mitts", en: "Bondage mitts", es: "Guantes de bondage", kind: 'directed' },
    { id: "thumb-cuffs", en: "Thumb cuffs", es: "Esposas de pulgares", kind: 'directed' },
    { id: "blindfold", en: "Blindfold", es: "Venda en los ojos", kind: 'directed' },
    { id: "earplugs-sensory-deprivation", en: "Earplugs / reduced hearing", es: "Tapones / reducción auditiva", kind: 'directed' },
    { id: "hood", en: "Bondage hood", es: "Capucha de bondage", kind: 'directed' },
    { id: "gag", en: "Gag", es: "Mordaza", kind: 'directed' },
    { id: "ball-gag", en: "Ball gag", es: "Mordaza de bola", kind: 'directed' },
    { id: "bit-gag", en: "Bit gag", es: "Mordaza de bocado", kind: 'directed' },
    { id: "ring-gag", en: "Ring gag", es: "Mordaza de aro", kind: 'directed' },
    { id: "rope-gag", en: "Rope gag", es: "Mordaza de cuerda", kind: 'directed' },
    { id: "furniture-restraint", en: "Bondage furniture restraint", es: "Restricción en mobiliario BDSM", kind: 'directed' },
    { id: "stocks-restraint", en: "Stocks restraint", es: "Cepo / stocks", kind: 'directed' },
    { id: "cage-confinement", en: "Cage confinement", es: "Confinamiento en jaula", kind: 'directed' },
  ],
};

export const PSYCHOLOGICAL: CatalogueCategorySeed = {
  id: "psychological",
  en: "Psychological play",
  es: "Juego psicológico",
  descriptionEn: "Consensual humiliation, praise, objectification, anticipation and psychological dynamics.",
  descriptionEs: "Humillación, elogio, objetificación, anticipación y dinámicas psicológicas consensuadas.",
  order: 13,
  practices: [
    { id: "humiliation", en: "Erotic humiliation", es: "Humillación erótica", kind: 'directed' },
    { id: "degradation", en: "Degradation", es: "Degradación", kind: 'directed' },
    { id: "praise-kink", en: "Praise", es: "Elogios", kind: 'directed' },
    { id: "body-worship", en: "Body worship", es: "Adoración del cuerpo", kind: 'directed' },
    { id: "foot-worship", en: "Foot worship", es: "Adoración de pies", kind: 'directed' },
    { id: "boot-worship", en: "Boot worship", es: "Adoración de botas", kind: 'directed' },
    { id: "objectification", en: "Objectification", es: "Objetificación", kind: 'directed' },
    { id: "furniture-roleplay", en: "Human furniture roleplay", es: "Roleplay de mueble humano", kind: 'directed' },
    { id: "begging", en: "Begging", es: "Suplicar", kind: 'power' },
    { id: "pleading", en: "Pleading", es: "Rogar", kind: 'power' },
    { id: "teasing-verbal", en: "Verbal teasing", es: "Provocación verbal", kind: 'directed' },
    { id: "dirty-talk", en: "Dirty talk", es: "Dirty talk", kind: 'directed' },
    { id: "name-calling", en: "Consensual name-calling", es: "Insultos consensuados", kind: 'directed' },
    { id: "mocking", en: "Consensual mocking", es: "Burlas consensuadas", kind: 'directed' },
    { id: "embarrassment-play", en: "Embarrassment play", es: "Juego con la vergüenza", kind: 'directed' },
    { id: "exposure-humiliation", en: "Consensual exposure humiliation", es: "Humillación por exposición consensuada", kind: 'directed' },
    { id: "small-penis-humiliation", en: "Small-penis humiliation fantasy", es: "Fantasía de humillación por pene pequeño", kind: 'directed' },
    { id: "breast-size-humiliation", en: "Breast-size humiliation fantasy", es: "Fantasía de humillación por tamaño de pecho", kind: 'directed' },
    { id: "orgasm-humiliation", en: "Orgasm humiliation", es: "Humillación relacionada con el orgasmo", kind: 'directed' },
    { id: "anticipation", en: "Anticipation and suspense", es: "Anticipación y suspense", kind: 'directed' },
    { id: "fear-play", en: "Consensual fear play", es: "Juego consensuado con miedo", kind: 'directed' },
    { id: "interrogation", en: "Interrogation dynamic", es: "Dinámica de interrogatorio", kind: 'power' },
    { id: "blackmail-roleplay", en: "Consensual blackmail roleplay", es: "Roleplay consensuado de chantaje", kind: 'power' },
    { id: "mind-games", en: "Consensual mind games", es: "Juegos mentales consensuados", kind: 'directed' },
    { id: "brat-dynamic", en: "Brat / brat-tamer dynamic", es: "Dinámica brat / brat-tamer", kind: 'power' },
    { id: "competitive-sex", en: "Competitive sexual play", es: "Juego sexual competitivo", kind: 'mutual' },
    { id: "worship-dynamic", en: "Worship dynamic", es: "Dinámica de adoración", kind: 'power' },
  ],
};

export const SENSATION: CatalogueCategorySeed = {
  id: "sensation",
  en: "Impact, pain & sensation",
  es: "Impacto, dolor y sensaciones",
  descriptionEn: "Impact, pressure, temperature and other consensual sensation play.",
  descriptionEs: "Impacto, presión, temperatura y otros juegos consensuados con sensaciones.",
  order: 14,
  practices: [
    { id: "spanking", en: "Spanking", es: "Azotes", kind: 'directed' },
    { id: "slapping-body", en: "Body slapping", es: "Bofetadas en el cuerpo", kind: 'directed' },
    { id: "face-slapping", en: "Face slapping", es: "Bofetadas en la cara", kind: 'directed' },
    { id: "paddling", en: "Paddling", es: "Pala / paddle", kind: 'directed' },
    { id: "flogging", en: "Flogging", es: "Flogger", kind: 'directed' },
    { id: "whipping", en: "Whipping", es: "Látigo", kind: 'directed' },
    { id: "caning", en: "Caning", es: "Vara / cane", kind: 'directed' },
    { id: "cropping", en: "Riding crop", es: "Fusta", kind: 'directed' },
    { id: "belting", en: "Belt impact", es: "Golpes con cinturón", kind: 'directed' },
    { id: "wooden-spoon-impact", en: "Wooden-spoon impact", es: "Golpes con cuchara de madera", kind: 'directed' },
    { id: "biting", en: "Biting", es: "Mordiscos", kind: 'directed' },
    { id: "scratching", en: "Scratching", es: "Arañazos", kind: 'directed' },
    { id: "pinching", en: "Pinching", es: "Pellizcos", kind: 'directed' },
    { id: "hair-pulling", en: "Hair pulling", es: "Tirones de pelo", kind: 'directed' },
    { id: "nipple-pinching", en: "Nipple pinching", es: "Pellizcos en pezones", kind: 'directed' },
    { id: "genital-slapping", en: "Genital slapping", es: "Golpes en genitales", kind: 'directed' },
    { id: "breast-slapping", en: "Breast slapping", es: "Golpes en el pecho", kind: 'directed' },
    { id: "butt-slapping", en: "Butt slapping", es: "Golpes en los glúteos", kind: 'directed' },
    { id: "ice-play", en: "Ice play", es: "Juego con hielo", kind: 'directed' },
    { id: "warm-wax", en: "Warm wax play", es: "Juego con cera templada", kind: 'directed' },
    { id: "temperature-contrast", en: "Temperature contrast", es: "Contraste de temperatura", kind: 'directed' },
    { id: "tickling", en: "Tickling", es: "Cosquillas", kind: 'directed' },
    { id: "feather-sensation", en: "Feather sensation", es: "Sensaciones con plumas", kind: 'directed' },
    { id: "rough-grabbing", en: "Rough grabbing", es: "Agarrones intensos", kind: 'directed' },
    { id: "pressure-points", en: "Pressure-point sensation", es: "Sensación en puntos de presión", kind: 'directed' },
    { id: "clothespins", en: "Clothespins", es: "Pinzas de ropa", kind: 'directed' },
    { id: "nipple-clamp-sensation", en: "Nipple-clamp sensation", es: "Sensación con pinzas de pezones", kind: 'directed' },
    { id: "electrostimulation-mild", en: "Mild electrostimulation", es: "Electroestimulación suave", kind: 'directed' },
    { id: "sensory-deprivation", en: "Sensory deprivation", es: "Privación sensorial", kind: 'directed' },
    { id: "sensory-overload", en: "Sensory overload", es: "Sobrecarga sensorial", kind: 'directed' },
    { id: "rough-body-play", en: "Rough body play", es: "Juego corporal intenso", kind: 'mutual' },
  ],
};
