import { CatalogueCategorySeed } from './types';

export const PENETRATION: CatalogueCategorySeed = {
  id: "penetration",
  en: "Penetration",
  es: "Penetración",
  descriptionEn: "Vaginal, anal and other penetrative practices and positions.",
  descriptionEs: "Prácticas y posiciones de penetración vaginal, anal y otras.",
  order: 4,
  practices: [
    { id: "vaginal-penetration", en: "Vaginal penetration", es: "Penetración vaginal", kind: 'directed', counterpartScoped: true, anatomySex: 'female' },
    { id: "anal-penetration", en: "Anal penetration", es: "Penetración anal", kind: 'directed', counterpartScoped: true },
    { id: "shallow-penetration", en: "Shallow penetration", es: "Penetración superficial", kind: 'directed', counterpartScoped: true },
    { id: "deep-penetration", en: "Deep penetration", es: "Penetración profunda", kind: 'directed', counterpartScoped: true },
    { id: "slow-penetration", en: "Slow penetration", es: "Penetración lenta", kind: 'directed', counterpartScoped: true },
    { id: "rough-penetration", en: "Rough penetration", es: "Penetración intensa", kind: 'directed', counterpartScoped: true },
    { id: "missionary", en: "Missionary position", es: "Postura del misionero", kind: 'mutual', counterpartScoped: true },
    { id: "cowgirl", en: "Cowgirl position", es: "Postura de vaquera", kind: 'mutual', counterpartScoped: true },
    { id: "reverse-cowgirl", en: "Reverse cowgirl", es: "Vaquera invertida", kind: 'mutual', counterpartScoped: true },
    { id: "doggy-style", en: "Doggy style", es: "A cuatro patas", kind: 'mutual', counterpartScoped: true },
    { id: "spooning-penetration", en: "Spooning penetration", es: "Penetración en cucharita", kind: 'mutual', counterpartScoped: true },
    { id: "standing-penetration", en: "Standing penetration", es: "Penetración de pie", kind: 'mutual', counterpartScoped: true },
    { id: "seated-penetration", en: "Seated penetration", es: "Penetración sentados", kind: 'mutual', counterpartScoped: true },
    { id: "against-wall", en: "Penetration against a wall", es: "Penetración contra la pared", kind: 'mutual', counterpartScoped: true },
    { id: "from-behind", en: "Penetration from behind", es: "Penetración desde atrás", kind: 'mutual', counterpartScoped: true },
    { id: "legs-on-shoulders", en: "Legs on shoulders", es: "Piernas sobre los hombros", kind: 'mutual', counterpartScoped: true },
    { id: "lotus-position", en: "Lotus position", es: "Postura del loto", kind: 'mutual', counterpartScoped: true },
    { id: "double-penetration", en: "Double penetration", es: "Doble penetración", kind: 'mutual', counterpartScoped: true },
    { id: "double-vaginal-penetration", en: "Double vaginal penetration", es: "Doble penetración vaginal", kind: 'mutual', counterpartScoped: true },
    { id: "double-anal-penetration", en: "Double anal penetration", es: "Doble penetración anal", kind: 'mutual', counterpartScoped: true },
    { id: "fisting-vaginal", en: "Vaginal fisting", es: "Fisting vaginal", kind: 'directed', counterpartScoped: true },
    { id: "fisting-anal", en: "Anal fisting", es: "Fisting anal", kind: 'directed', counterpartScoped: true },
    { id: "prostate-penetration", en: "Prostate-focused penetration", es: "Penetración orientada a próstata", kind: 'directed', counterpartScoped: true, anatomySex: 'male' },
    { id: "cervix-contact", en: "Deep cervical contact", es: "Contacto cervical profundo", kind: 'directed', counterpartScoped: true },
    { id: "penetration-without-orgasm", en: "Penetration without orgasm", es: "Penetración sin orgasmo", kind: 'mutual', counterpartScoped: true },
    { id: "creampie-vaginal", en: "Vaginal internal ejaculation", es: "Eyaculación interna vaginal", kind: 'directed', counterpartScoped: true, anatomySex: 'female' },
    { id: "creampie-anal", en: "Anal internal ejaculation", es: "Eyaculación interna anal", kind: 'directed', counterpartScoped: true },
  ],
};

export const TOYS: CatalogueCategorySeed = {
  id: "toys",
  en: "Toys & accessories",
  es: "Juguetes y accesorios",
  descriptionEn: "Solo and partnered use of toys, with body-site preferences where relevant.",
  descriptionEs: "Uso individual o en pareja de juguetes, con preferencias de zona corporal cuando corresponde.",
  order: 5,
  practices: [
    { id: "vibrator", en: "Vibrator", es: "Vibrador", kind: 'toy', targetSites: ['external-genitals', 'vaginal', 'anal', 'nipples', 'body'] },
    { id: "wand-vibrator", en: "Wand vibrator", es: "Vibrador tipo wand", kind: 'toy', targetSites: ['external-genitals', 'nipples', 'body'] },
    { id: "bullet-vibrator", en: "Bullet vibrator", es: "Vibrador bala", kind: 'toy', targetSites: ['external-genitals', 'vaginal', 'anal', 'nipples', 'body'] },
    { id: "rabbit-vibrator", en: "Rabbit vibrator", es: "Vibrador rabbit", kind: 'toy', targetSites: ['external-genitals', 'vaginal'] },
    { id: "dildo", en: "Dildo", es: "Dildo", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "realistic-dildo", en: "Realistic dildo", es: "Dildo realista", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "glass-dildo", en: "Glass dildo", es: "Dildo de cristal", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "metal-dildo", en: "Metal dildo", es: "Dildo metálico", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "double-ended-dildo", en: "Double-ended dildo", es: "Dildo doble", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "anal-plug", en: "Anal plug", es: "Plug anal", kind: 'toy', targetSites: ['anal'] },
    { id: "vibrating-anal-plug", en: "Vibrating anal plug", es: "Plug anal vibrador", kind: 'toy', targetSites: ['anal'] },
    { id: "anal-beads", en: "Anal beads", es: "Bolas anales", kind: 'toy', targetSites: ['anal'] },
    { id: "prostate-massager", en: "Prostate massager", es: "Masajeador de próstata", kind: 'toy', targetSites: ['anal'] },
    { id: "butt-plug-tail", en: "Tail plug", es: "Plug con cola", kind: 'toy', targetSites: ['anal'] },
    { id: "strap-on", en: "Strap-on", es: "Strap-on", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "strapless-strap-on", en: "Strapless strap-on", es: "Strap-on sin arnés", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "penis-sleeve", en: "Penis sleeve", es: "Funda para pene", kind: 'toy', targetSites: ['penis'] },
    { id: "cock-ring", en: "Cock ring", es: "Anillo para pene", kind: 'toy', targetSites: ['penis'] },
    { id: "vibrating-cock-ring", en: "Vibrating cock ring", es: "Anillo vibrador", kind: 'toy', targetSites: ['penis'] },
    { id: "masturbator-sleeve", en: "Masturbation sleeve", es: "Masturbador tipo funda", kind: 'toy', targetSites: ['penis'] },
    { id: "automatic-masturbator", en: "Automatic masturbator", es: "Masturbador automático", kind: 'toy', targetSites: ['penis'] },
    { id: "penis-pump", en: "Penis pump", es: "Bomba de pene", kind: 'toy', targetSites: ['penis'] },
    { id: "vulva-suction-toy", en: "Vulva suction toy", es: "Succionador de vulva", kind: 'toy', targetSites: ['external-genitals', 'vaginal', 'anal', 'nipples', 'body'] },
    { id: "clitoral-suction-toy", en: "Clitoral suction toy", es: "Succionador de clítoris", kind: 'toy', targetSites: ['external-genitals', 'vaginal', 'anal', 'nipples', 'body'] },
    { id: "kegel-balls", en: "Kegel balls", es: "Bolas Kegel", kind: 'toy', targetSites: ['external-genitals', 'vaginal'] },
    { id: "remote-control-toy", en: "Remote-control toy", es: "Juguete por control remoto", kind: 'toy', targetSites: ['external-genitals', 'vaginal', 'anal', 'nipples', 'body'] },
    { id: "app-controlled-toy", en: "App-controlled toy", es: "Juguete controlado por app", kind: 'toy', targetSites: ['external-genitals', 'vaginal', 'anal', 'nipples', 'body'] },
    { id: "wearable-vibrator", en: "Wearable vibrator", es: "Vibrador wearable", kind: 'toy', targetSites: ['external-genitals', 'vaginal', 'anal', 'nipples', 'body'] },
    { id: "sex-machine", en: "Sex machine", es: "Máquina sexual", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "nipple-clamps", en: "Nipple clamps", es: "Pinzas para pezones", kind: 'toy', targetSites: ['nipples'] },
    { id: "nipple-suction-cups", en: "Nipple suction cups", es: "Ventosas para pezones", kind: 'toy', targetSites: ['nipples'] },
    { id: "feather-tickler", en: "Feather tickler", es: "Plumero de cosquillas", kind: 'toy', targetSites: ['body'] },
    { id: "pinwheel", en: "Wartenberg wheel", es: "Rueda de Wartenberg", kind: 'toy', targetSites: ['body'] },
    { id: "blindfold-accessory", en: "Blindfold as accessory", es: "Venda como accesorio", kind: 'toy', targetSites: ['body'] },
    { id: "gag-accessory", en: "Gag as accessory", es: "Mordaza como accesorio", kind: 'toy', targetSites: ['mouth'] },
    { id: "sex-furniture", en: "Sex furniture", es: "Mobiliario sexual", kind: 'mutual' },
    { id: "sex-swing", en: "Sex swing", es: "Columpio sexual", kind: 'mutual' },
    { id: "positioning-pillow", en: "Positioning pillow", es: "Cojín de posicionamiento", kind: 'mutual' },
    { id: "vacuum-cup-toys", en: "Suction-mounted toys", es: "Juguetes con ventosa", kind: 'toy', targetSites: ['mouth', 'vaginal', 'anal'] },
    { id: "temperature-toys", en: "Temperature-play toys", es: "Juguetes de temperatura", kind: 'toy', targetSites: ['body'] },
  ],
};

export const ORGASM_CONTROL: CatalogueCategorySeed = {
  id: "orgasm-control",
  en: "Orgasm, teasing & sexual control",
  es: "Orgasmo, teasing y control sexual",
  descriptionEn: "Orgasm timing, teasing, edging, denial and consensual sexual control.",
  descriptionEs: "Control del momento del orgasmo, teasing, edging, negación y control sexual consensuado.",
  order: 6,
  practices: [
    { id: "edging", en: "Edging", es: "Edging", kind: 'directed' },
    { id: "orgasm-denial", en: "Orgasm denial", es: "Negación del orgasmo", kind: 'directed' },
    { id: "orgasm-control", en: "Orgasm control", es: "Control del orgasmo", kind: 'directed' },
    { id: "permission-to-orgasm", en: "Requiring permission to orgasm", es: "Pedir permiso para correrse", kind: 'power' },
    { id: "multiple-orgasms", en: "Multiple orgasms", es: "Orgasmos múltiples", kind: 'directed' },
    { id: "forced-orgasm", en: "Consensual forced orgasm", es: "Orgasmo forzado consensuado", kind: 'directed' },
    { id: "ruined-orgasm", en: "Ruined orgasm", es: "Orgasmo arruinado", kind: 'directed' },
    { id: "tease-and-denial", en: "Tease and denial", es: "Provocación y negación", kind: 'directed' },
    { id: "long-edging-session", en: "Long edging sessions", es: "Sesiones largas de edging", kind: 'directed' },
    { id: "countdown-orgasm", en: "Orgasm countdown", es: "Cuenta atrás para el orgasmo", kind: 'power' },
    { id: "simultaneous-orgasm", en: "Simultaneous orgasm", es: "Orgasmo simultáneo", kind: 'mutual' },
    { id: "orgasm-on-command", en: "Orgasm on command", es: "Correrse a la orden", kind: 'power' },
    { id: "no-orgasm-sex", en: "Sex without orgasm", es: "Sexo sin orgasmo", kind: 'mutual' },
    { id: "delayed-orgasm", en: "Deliberately delayed orgasm", es: "Retrasar deliberadamente el orgasmo", kind: 'mutual' },
    { id: "orgasm-through-penetration", en: "Orgasm through penetration", es: "Orgasmo mediante penetración", kind: 'mutual' },
    { id: "orgasm-through-oral", en: "Orgasm through oral sex", es: "Orgasmo mediante sexo oral", kind: 'mutual' },
    { id: "orgasm-through-toys", en: "Orgasm through toys", es: "Orgasmo mediante juguetes", kind: 'mutual' },
    { id: "hands-free-orgasm", en: "Hands-free orgasm", es: "Orgasmo sin manos", kind: 'mutual' },
    { id: "partner-decides-orgasm", en: "Partner decides when I orgasm", es: "Que la pareja decida cuándo me corro", kind: 'power' },
    { id: "decide-partner-orgasm", en: "Deciding when my partner orgasms", es: "Decidir cuándo se corre mi pareja", kind: 'power' },
    { id: "post-orgasm-stimulation", en: "Stimulation after orgasm", es: "Estimulación después del orgasmo", kind: 'directed' },
    { id: "overstimulation", en: "Overstimulation", es: "Sobreestimulación", kind: 'directed' },
  ],
};

export const BODY_FETISHES: CatalogueCategorySeed = {
  id: "body-fetishes",
  en: "Body focus & fetishes",
  es: "Fetiches y foco corporal",
  descriptionEn: "Preferences focused on body parts, features, scents and sensory attraction.",
  descriptionEs: "Preferencias centradas en partes del cuerpo, rasgos, olores y atracción sensorial.",
  order: 7,
  practices: [
    { id: "feet", en: "Feet", es: "Pies", kind: 'focus' },
    { id: "toes", en: "Toes", es: "Dedos de los pies", kind: 'focus' },
    { id: "hands", en: "Hands", es: "Manos", kind: 'focus' },
    { id: "fingers", en: "Fingers", es: "Dedos de las manos", kind: 'focus' },
    { id: "legs", en: "Legs", es: "Piernas", kind: 'focus' },
    { id: "thighs", en: "Thighs", es: "Muslos", kind: 'focus' },
    { id: "buttocks", en: "Buttocks", es: "Glúteos", kind: 'focus' },
    { id: "breasts", en: "Breasts", es: "Pecho / senos", kind: 'focus' },
    { id: "nipples", en: "Nipples", es: "Pezones", kind: 'focus' },
    { id: "chest", en: "Chest", es: "Pecho", kind: 'focus' },
    { id: "penis", en: "Penis", es: "Pene", kind: 'focus' },
    { id: "vulva", en: "Vulva", es: "Vulva", kind: 'focus' },
    { id: "testicles", en: "Testicles", es: "Testículos", kind: 'focus' },
    { id: "pubic-hair", en: "Pubic hair", es: "Vello púbico", kind: 'focus' },
    { id: "body-hair", en: "Body hair", es: "Vello corporal", kind: 'focus' },
    { id: "armpits", en: "Armpits", es: "Axilas", kind: 'focus' },
    { id: "neck", en: "Neck", es: "Cuello", kind: 'focus' },
    { id: "ears", en: "Ears", es: "Orejas", kind: 'focus' },
    { id: "lips", en: "Lips", es: "Labios", kind: 'focus' },
    { id: "tongue", en: "Tongue", es: "Lengua", kind: 'focus' },
    { id: "hair", en: "Hair", es: "Pelo", kind: 'focus' },
    { id: "muscles", en: "Muscles", es: "Musculatura", kind: 'focus' },
    { id: "bellies", en: "Bellies", es: "Vientre", kind: 'focus' },
    { id: "navel", en: "Navel", es: "Ombligo", kind: 'focus' },
    { id: "body-scent", en: "Natural body scent", es: "Olor corporal natural", kind: 'focus' },
    { id: "sweat", en: "Sweat", es: "Sudor", kind: 'focus' },
    { id: "underwear", en: "Underwear", es: "Ropa interior", kind: 'focus' },
    { id: "worn-underwear", en: "Worn underwear", es: "Ropa interior usada", kind: 'focus' },
    { id: "tattoos", en: "Tattoos", es: "Tatuajes", kind: 'focus' },
    { id: "piercings", en: "Piercings", es: "Piercings", kind: 'focus' },
  ],
};
