import { CatalogueCategorySeed } from './types';

export const GROUPS: CatalogueCategorySeed = {
  id: "groups",
  en: "Partners, groups & composition",
  es: "Parejas, grupos y composición",
  descriptionEn: "Multiple-partner configurations and consensual group dynamics.",
  descriptionEs: "Configuraciones con varias parejas y dinámicas grupales consensuadas.",
  order: 8,
  practices: [
    { id: "threesome-mmf", en: "Threesome: two men and one woman", es: "Trío: dos hombres y una mujer", kind: 'mutual' },
    { id: "threesome-mff", en: "Threesome: one man and two women", es: "Trío: un hombre y dos mujeres", kind: 'mutual' },
    { id: "threesome-mmm", en: "Threesome: three men", es: "Trío: tres hombres", kind: 'mutual' },
    { id: "threesome-fff", en: "Threesome: three women", es: "Trío: tres mujeres", kind: 'mutual' },
    { id: "foursome", en: "Foursome", es: "Cuarteto", kind: 'mutual' },
    { id: "group-sex", en: "Group sex", es: "Sexo en grupo", kind: 'mutual' },
    { id: "orgy", en: "Orgy", es: "Orgía", kind: 'mutual' },
    { id: "gangbang", en: "Gangbang", es: "Gangbang", kind: 'group' },
    { id: "reverse-gangbang", en: "Reverse gangbang", es: "Gangbang inverso", kind: 'group' },
    { id: "being-center-of-group", en: "Being the center of a group", es: "Ser el centro de un grupo", kind: 'group' },
    { id: "participating-around-center", en: "Participating around a group center", es: "Participar alrededor de una persona central", kind: 'group' },
    { id: "partner-swapping", en: "Partner swapping", es: "Intercambio de parejas", kind: 'mutual' },
    { id: "swinging", en: "Swinging", es: "Swinger", kind: 'mutual' },
    { id: "soft-swap", en: "Soft swap", es: "Intercambio suave", kind: 'mutual' },
    { id: "full-swap", en: "Full swap", es: "Intercambio completo", kind: 'mutual' },
    { id: "same-room-sex", en: "Sex beside another couple", es: "Sexo junto a otra pareja", kind: 'mutual' },
    { id: "watching-partner-with-other", en: "Watching a partner with someone else", es: "Ver a la pareja con otra persona", kind: 'watch' },
    { id: "being-watched-with-other", en: "Being watched by a partner with someone else", es: "Que la pareja mire mientras estás con otra persona", kind: 'watch' },
    { id: "hotwife-dynamic", en: "Hotwife dynamic", es: "Dinámica hotwife", kind: 'mutual' },
    { id: "cuckold-dynamic", en: "Cuckold dynamic", es: "Dinámica cuckold", kind: 'mutual' },
    { id: "cuckquean-dynamic", en: "Cuckquean dynamic", es: "Dinámica cuckquean", kind: 'mutual' },
    { id: "polysexual-scene", en: "Multi-partner sexual scene", es: "Escena sexual con varias parejas", kind: 'mutual' },
    { id: "anonymous-group-scene", en: "Anonymous consensual group scene", es: "Escena grupal consensuada con anonimato", kind: 'mutual' },
    { id: "couple-plus-guest", en: "Couple with a guest", es: "Pareja con invitado/a", kind: 'mutual' },
  ],
};

export const ROLEPLAY: CatalogueCategorySeed = {
  id: "roleplay",
  en: "Scenarios & roleplay",
  es: "Escenarios y roleplay",
  descriptionEn: "Consensual adult roleplay, characters and scene-based fantasies.",
  descriptionEs: "Roleplay adulto consensuado, personajes y fantasías basadas en escenas.",
  order: 9,
  practices: [
    { id: "roleplay-general", en: "General roleplay", es: "Roleplay general", kind: 'mutual' },
    { id: "strangers-roleplay", en: "Strangers roleplay", es: "Roleplay de desconocidos", kind: 'mutual' },
    { id: "first-date-roleplay", en: "First-date roleplay", es: "Roleplay de primera cita", kind: 'mutual' },
    { id: "boss-employee-roleplay", en: "Boss / employee roleplay", es: "Roleplay jefe / empleado", kind: 'mutual' },
    { id: "teacher-student-adult-roleplay", en: "Adult teacher / adult student roleplay", es: "Roleplay profesor adulto / estudiante adulto", kind: 'mutual' },
    { id: "doctor-patient-roleplay", en: "Doctor / patient roleplay", es: "Roleplay médico / paciente", kind: 'mutual' },
    { id: "nurse-patient-roleplay", en: "Nurse / patient roleplay", es: "Roleplay enfermero/a / paciente", kind: 'mutual' },
    { id: "police-roleplay", en: "Police roleplay", es: "Roleplay policial", kind: 'mutual' },
    { id: "prisoner-guard-roleplay", en: "Prisoner / guard roleplay", es: "Roleplay prisionero / guardia", kind: 'mutual' },
    { id: "captor-captive-roleplay", en: "Consensual captor / captive roleplay", es: "Roleplay consensuado captor / cautivo", kind: 'mutual' },
    { id: "royalty-servant-roleplay", en: "Royalty / servant roleplay", es: "Roleplay realeza / sirviente", kind: 'mutual' },
    { id: "celebrity-fan-roleplay", en: "Celebrity / fan roleplay", es: "Roleplay famoso / fan", kind: 'mutual' },
    { id: "massage-roleplay", en: "Massage roleplay", es: "Roleplay de masaje", kind: 'mutual' },
    { id: "delivery-person-roleplay", en: "Delivery-person roleplay", es: "Roleplay de repartidor/a", kind: 'mutual' },
    { id: "hotel-roleplay", en: "Hotel encounter roleplay", es: "Roleplay de encuentro en hotel", kind: 'mutual' },
    { id: "office-roleplay", en: "Office roleplay", es: "Roleplay de oficina", kind: 'mutual' },
    { id: "fantasy-character-roleplay", en: "Fantasy character roleplay", es: "Roleplay de personajes de fantasía", kind: 'mutual' },
    { id: "superhero-roleplay", en: "Superhero roleplay", es: "Roleplay de superhéroes", kind: 'mutual' },
    { id: "vampire-roleplay", en: "Vampire roleplay", es: "Roleplay de vampiros", kind: 'mutual' },
    { id: "monster-roleplay", en: "Monster fantasy roleplay", es: "Roleplay de fantasía monstruosa", kind: 'mutual' },
    { id: "pet-play", en: "Pet play", es: "Pet play", kind: 'power' },
    { id: "primal-play", en: "Primal play", es: "Primal play", kind: 'mutual' },
    { id: "consensual-non-consent-roleplay", en: "Consensual non-consent roleplay", es: "Roleplay de no consentimiento consensuado", kind: 'mutual' },
    { id: "sleep-roleplay", en: "Consensual sleep roleplay", es: "Roleplay consensuado de sueño", kind: 'mutual' },
    { id: "kidnapping-roleplay", en: "Consensual kidnapping roleplay", es: "Roleplay consensuado de secuestro", kind: 'mutual' },
    { id: "interrogation-roleplay", en: "Interrogation roleplay", es: "Roleplay de interrogatorio", kind: 'power' },
    { id: "ritual-roleplay", en: "Ritual or ceremonial roleplay", es: "Roleplay ritual o ceremonial", kind: 'mutual' },
  ],
};

export const EXHIBITIONISM: CatalogueCategorySeed = {
  id: "exhibitionism",
  en: "Exhibitionism, voyeurism & places",
  es: "Exhibicionismo, voyeurismo y lugares",
  descriptionEn: "Consensual watching, being watched, recording and location-based scenarios.",
  descriptionEs: "Mirar, ser observado, grabación consentida y escenarios ligados a lugares.",
  order: 10,
  practices: [
    { id: "voyeurism", en: "Voyeurism", es: "Voyeurismo", kind: 'watch' },
    { id: "being-watched", en: "Being watched", es: "Ser observado/a", kind: 'watch' },
    { id: "partner-watching", en: "Partner watching", es: "Que mire la pareja", kind: 'watch' },
    { id: "watching-partner", en: "Watching a partner", es: "Mirar a la pareja", kind: 'watch' },
    { id: "private-recording", en: "Private consensual recording", es: "Grabación privada consensuada", kind: 'mutual' },
    { id: "taking-erotic-photos", en: "Taking erotic photos", es: "Hacer fotos eróticas", kind: 'directed' },
    { id: "posing-for-erotic-photos", en: "Posing for erotic photos", es: "Posar para fotos eróticas", kind: 'directed' },
    { id: "video-call-sex", en: "Sex over video call", es: "Sexo por videollamada", kind: 'mutual' },
    { id: "webcam-performance-private", en: "Private webcam performance", es: "Actuación privada por webcam", kind: 'watch' },
    { id: "mirrors", en: "Sex in front of mirrors", es: "Sexo frente a espejos", kind: 'mutual' },
    { id: "lights-on", en: "Sex with the lights on", es: "Sexo con la luz encendida", kind: 'mutual' },
    { id: "curtains-open-private", en: "Visible-from-outside fantasy in a private setting", es: "Fantasía de poder ser visto desde un espacio privado", kind: 'mutual' },
    { id: "sex-in-car", en: "Sex in a car", es: "Sexo en el coche", kind: 'mutual' },
    { id: "sex-in-shower", en: "Sex in the shower", es: "Sexo en la ducha", kind: 'mutual' },
    { id: "sex-in-bath", en: "Sex in the bath", es: "Sexo en la bañera", kind: 'mutual' },
    { id: "sex-in-kitchen", en: "Sex in the kitchen", es: "Sexo en la cocina", kind: 'mutual' },
    { id: "sex-on-sofa", en: "Sex on a sofa", es: "Sexo en el sofá", kind: 'mutual' },
    { id: "sex-on-floor", en: "Sex on the floor", es: "Sexo en el suelo", kind: 'mutual' },
    { id: "sex-in-hotel", en: "Sex in a hotel", es: "Sexo en un hotel", kind: 'mutual' },
    { id: "sex-outdoors-private", en: "Sex outdoors in a private place", es: "Sexo al aire libre en lugar privado", kind: 'mutual' },
    { id: "semi-public-consensual-scene", en: "Semi-public consensual scene", es: "Escena consensuada en lugar semipúblico", kind: 'mutual' },
    { id: "sex-club", en: "Sex club", es: "Club sexual", kind: 'mutual' },
    { id: "dungeon-venue", en: "BDSM dungeon venue", es: "Local / dungeon BDSM", kind: 'mutual' },
    { id: "glory-hole", en: "Glory-hole scenario", es: "Escenario de glory hole", kind: 'directed' },
    { id: "anonymous-encounter-roleplay", en: "Anonymous encounter fantasy", es: "Fantasía de encuentro anónimo", kind: 'mutual' },
  ],
};
