import { CatalogueCategorySeed } from './types';

export const AFFECTION_INTIMACY: CatalogueCategorySeed = {
  id: "affection-intimacy",
  en: "Affection & intimacy",
  es: "Afecto e intimidad",
  descriptionEn: "Affectionate and sexual connection from gentle contact to shared intimacy.",
  descriptionEs: "Conexión afectiva y sexual, desde el contacto suave hasta la intimidad compartida.",
  order: 0,
  practices: [
    { id: "kissing", en: "Kissing", es: "Besos", kind: 'directed', counterpartScoped: true },
    { id: "making-out", en: "Making out", es: "Besarse intensamente", kind: 'mutual', counterpartScoped: true },
    { id: "cuddling", en: "Cuddling", es: "Abrazos y mimos", kind: 'mutual', counterpartScoped: true },
    { id: "spooning", en: "Spooning", es: "Dormir o estar en cucharita", kind: 'mutual', counterpartScoped: true },
    { id: "holding-hands", en: "Holding hands", es: "Cogerse de la mano", kind: 'mutual', counterpartScoped: true },
    { id: "hair-stroking", en: "Hair stroking", es: "Acariciar el pelo", kind: 'directed', counterpartScoped: true },
    { id: "face-caressing", en: "Face caressing", es: "Acariciar la cara", kind: 'directed', counterpartScoped: true },
    { id: "back-rubs", en: "Back rubs", es: "Caricias en la espalda", kind: 'directed', counterpartScoped: true },
    { id: "sensual-massage", en: "Sensual massage", es: "Masaje sensual", kind: 'directed', counterpartScoped: true },
    { id: "full-body-massage", en: "Full-body massage", es: "Masaje de cuerpo entero", kind: 'directed', counterpartScoped: true },
    { id: "showering-together", en: "Showering together", es: "Ducharse juntos", kind: 'mutual', counterpartScoped: true },
    { id: "bathing-together", en: "Bathing together", es: "Bañarse juntos", kind: 'mutual', counterpartScoped: true },
    { id: "sleeping-naked-together", en: "Sleeping naked together", es: "Dormir desnudos juntos", kind: 'mutual', counterpartScoped: true },
    { id: "skin-to-skin-contact", en: "Skin-to-skin contact", es: "Contacto piel con piel", kind: 'mutual', counterpartScoped: true },
    { id: "slow-sex", en: "Slow sex", es: "Sexo lento", kind: 'mutual', counterpartScoped: true },
    { id: "passionate-sex", en: "Passionate sex", es: "Sexo apasionado", kind: 'mutual', counterpartScoped: true },
    { id: "morning-sex", en: "Morning sex", es: "Sexo por la mañana", kind: 'mutual', counterpartScoped: true },
    { id: "sleepy-sex", en: "Sleepy consensual sex", es: "Sexo consensuado con sueño", kind: 'mutual', counterpartScoped: true },
    { id: "quickies", en: "Quickies", es: "Polvos rápidos", kind: 'mutual', counterpartScoped: true },
    { id: "extended-foreplay", en: "Extended foreplay", es: "Preliminares largos", kind: 'mutual', counterpartScoped: true },
    { id: "romantic-sex", en: "Romantic sex", es: "Sexo romántico", kind: 'mutual', counterpartScoped: true },
    { id: "playful-sex", en: "Playful sex", es: "Sexo juguetón", kind: 'mutual', counterpartScoped: true },
    { id: "verbal-affection", en: "Verbal affection", es: "Afecto verbal", kind: 'mutual', counterpartScoped: true },
    { id: "praise-during-sex", en: "Praise during sex", es: "Elogios durante el sexo", kind: 'directed', counterpartScoped: true },
    { id: "eye-contact", en: "Eye contact during intimacy", es: "Contacto visual durante la intimidad", kind: 'mutual', counterpartScoped: true },
  ],
};

export const CLOTHING_APPEARANCE: CatalogueCategorySeed = {
  id: "clothing-appearance",
  en: "Clothing, appearance & lingerie",
  es: "Ropa, apariencia y lencería",
  descriptionEn: "Clothing, styling, materials, uniforms and visual presentation.",
  descriptionEs: "Ropa, estilo, materiales, uniformes y presentación visual.",
  order: 1,
  practices: [
    { id: "lingerie", en: "Lingerie", es: "Lencería", kind: 'wear' },
    { id: "stockings", en: "Stockings", es: "Medias", kind: 'wear' },
    { id: "garter-belts", en: "Garter belts", es: "Ligas y portaligas", kind: 'wear' },
    { id: "thigh-highs", en: "Thigh-high socks", es: "Medias hasta el muslo", kind: 'wear' },
    { id: "high-heels", en: "High heels", es: "Tacones altos", kind: 'wear' },
    { id: "boots", en: "Boots", es: "Botas", kind: 'wear' },
    { id: "leather-clothing", en: "Leather clothing", es: "Ropa de cuero", kind: 'wear' },
    { id: "latex-clothing", en: "Latex clothing", es: "Ropa de látex", kind: 'wear' },
    { id: "pvc-clothing", en: "PVC clothing", es: "Ropa de PVC", kind: 'wear' },
    { id: "lace-clothing", en: "Lace clothing", es: "Ropa de encaje", kind: 'wear' },
    { id: "silk-satin", en: "Silk or satin", es: "Seda o satén", kind: 'wear' },
    { id: "corsets", en: "Corsets", es: "Corsés", kind: 'wear' },
    { id: "bodysuits", en: "Bodysuits", es: "Bodies", kind: 'wear' },
    { id: "harnesses-fashion", en: "Body harnesses", es: "Arneses corporales", kind: 'wear' },
    { id: "chokers", en: "Chokers", es: "Gargantillas", kind: 'wear' },
    { id: "collars-fashion", en: "Decorative collars", es: "Collares decorativos", kind: 'wear' },
    { id: "masks", en: "Masks", es: "Máscaras", kind: 'wear' },
    { id: "gloves", en: "Gloves", es: "Guantes", kind: 'wear' },
    { id: "suits", en: "Formal suits", es: "Trajes formales", kind: 'wear' },
    { id: "uniforms", en: "Uniforms", es: "Uniformes", kind: 'wear' },
    { id: "sportswear", en: "Sportswear", es: "Ropa deportiva", kind: 'wear' },
    { id: "cosplay", en: "Cosplay outfits", es: "Cosplay", kind: 'wear' },
    { id: "cross-dressing", en: "Cross-dressing", es: "Travestismo / ropa de otro género", kind: 'wear' },
    { id: "partial-nudity", en: "Partial nudity", es: "Desnudez parcial", kind: 'mutual' },
    { id: "full-nudity", en: "Full nudity", es: "Desnudez total", kind: 'mutual' },
    { id: "body-paint", en: "Body paint", es: "Pintura corporal", kind: 'wear' },
  ],
};

export const MANUAL_MASTURBATION: CatalogueCategorySeed = {
  id: "manual-masturbation",
  en: "Manual stimulation & masturbation",
  es: "Estimulación manual y masturbación",
  descriptionEn: "Hands, fingers and solo or partnered masturbation.",
  descriptionEs: "Manos, dedos y masturbación individual o en pareja.",
  order: 2,
  practices: [
    { id: "solo-masturbation", en: "Solo masturbation", es: "Masturbación en solitario", kind: 'mutual', counterpartScoped: true },
    { id: "masturbating-together", en: "Masturbating together", es: "Masturbarse juntos", kind: 'mutual', counterpartScoped: true },
    { id: "watch-partner-masturbate", en: "Watching a partner masturbate", es: "Ver masturbarse a la pareja", kind: 'watch' },
    { id: "mutual-handjobs", en: "Mutual hand stimulation", es: "Estimulación manual mutua", kind: 'mutual', counterpartScoped: true },
    { id: "handjob", en: "Handjob", es: "Masturbación manual del pene", kind: 'directed', counterpartScoped: true, anatomySex: 'male' },
    { id: "vulva-hand-stimulation", en: "Manual vulva stimulation", es: "Estimulación manual de la vulva", kind: 'directed', counterpartScoped: true, anatomySex: 'female' },
    { id: "clitoral-stimulation", en: "Clitoral stimulation", es: "Estimulación del clítoris", kind: 'directed', counterpartScoped: true, anatomySex: 'female' },
    { id: "fingering-vaginal", en: "Vaginal fingering", es: "Estimulación vaginal con dedos", kind: 'directed', counterpartScoped: true, anatomySex: 'female' },
    { id: "fingering-anal", en: "Anal fingering", es: "Estimulación anal con dedos", kind: 'directed', counterpartScoped: true },
    { id: "finger-sucking", en: "Finger sucking", es: "Chupar los dedos", kind: 'directed', counterpartScoped: true },
    { id: "hand-over-mouth", en: "Hand over mouth", es: "Mano sobre la boca", kind: 'directed', counterpartScoped: true },
    { id: "guided-touch", en: "Guided touching", es: "Guiar la mano de la pareja", kind: 'mutual', counterpartScoped: true },
    { id: "touching-over-clothes", en: "Touching over clothes", es: "Tocarse sobre la ropa", kind: 'directed', counterpartScoped: true },
    { id: "touching-under-clothes", en: "Touching under clothes", es: "Tocarse bajo la ropa", kind: 'directed', counterpartScoped: true },
    { id: "breast-stimulation-by-hand", en: "Manual breast stimulation", es: "Estimulación manual del pecho", kind: 'directed', counterpartScoped: true },
    { id: "nipple-stimulation-by-hand", en: "Manual nipple stimulation", es: "Estimulación manual de pezones", kind: 'directed', counterpartScoped: true },
    { id: "perineum-massage", en: "Perineum massage", es: "Masaje del perineo", kind: 'directed', counterpartScoped: true },
    { id: "prostate-massage-manual", en: "Manual prostate massage", es: "Masaje manual de próstata", kind: 'directed', counterpartScoped: true, anatomySex: 'male' },
    { id: "edging-manual", en: "Manual edging", es: "Edging manual", kind: 'directed', counterpartScoped: true },
    { id: "forced-masturbation-roleplay", en: "Consensual forced-masturbation roleplay", es: "Roleplay consensuado de masturbación forzada", kind: 'directed', counterpartScoped: true },
    { id: "hands-free-masturbation", en: "Hands-free masturbation", es: "Masturbación sin manos", kind: 'mutual', counterpartScoped: true },
    { id: "masturbation-in-front-of-partner", en: "Masturbating for a partner", es: "Masturbarse para la pareja", kind: 'watch' },
  ],
};

export const ORAL: CatalogueCategorySeed = {
  id: "oral",
  en: "Oral sex",
  es: "Sexo oral",
  descriptionEn: "Oral stimulation, positions and mouth-focused sexual practices.",
  descriptionEs: "Estimulación oral, posiciones y prácticas sexuales centradas en la boca.",
  order: 3,
  practices: [
    { id: "cunnilingus", en: "Cunnilingus", es: "Cunnilingus", kind: 'directed', counterpartScoped: true, anatomySex: 'female' },
    { id: "fellatio", en: "Fellatio", es: "Felación", kind: 'directed', counterpartScoped: true, anatomySex: 'male' },
    { id: "sixty-nine", en: "69", es: "69", kind: 'mutual', counterpartScoped: true },
    { id: "face-sitting", en: "Face sitting", es: "Face-sitting", kind: 'directed', counterpartScoped: true },
    { id: "deep-throat", en: "Deep throat", es: "Garganta profunda", kind: 'directed', counterpartScoped: true },
    { id: "throat-fucking", en: "Throat-focused oral penetration", es: "Penetración oral profunda", kind: 'directed', counterpartScoped: true },
    { id: "oral-teasing", en: "Oral teasing", es: "Provocación oral", kind: 'directed', counterpartScoped: true },
    { id: "oral-edging", en: "Oral edging", es: "Edging oral", kind: 'directed', counterpartScoped: true },
    { id: "licking-genitals", en: "Genital licking", es: "Lamer los genitales", kind: 'directed', counterpartScoped: true },
    { id: "sucking-genitals", en: "Genital sucking", es: "Succión genital", kind: 'directed', counterpartScoped: true },
    { id: "oral-anal", en: "Anilingus / rimming", es: "Anilingus / rimming", kind: 'directed', counterpartScoped: true },
    { id: "oral-nipples", en: "Oral nipple stimulation", es: "Estimulación oral de pezones", kind: 'directed', counterpartScoped: true },
    { id: "oral-breasts", en: "Oral breast stimulation", es: "Estimulación oral del pecho", kind: 'directed', counterpartScoped: true },
    { id: "oral-fingers", en: "Sucking fingers", es: "Chupar los dedos", kind: 'directed', counterpartScoped: true },
    { id: "oral-toes", en: "Sucking toes", es: "Chupar los dedos de los pies", kind: 'directed', counterpartScoped: true },
    { id: "saliva-during-oral", en: "Using saliva during oral sex", es: "Uso de saliva durante el sexo oral", kind: 'mutual', counterpartScoped: true },
    { id: "cum-in-mouth", en: "Ejaculation in mouth", es: "Eyaculación en la boca", kind: 'directed', counterpartScoped: true },
    { id: "swallowing-semen", en: "Swallowing semen", es: "Tragar semen", kind: 'directed', counterpartScoped: true },
    { id: "spitting-semen", en: "Spitting semen after oral", es: "Escupir semen después del sexo oral", kind: 'directed', counterpartScoped: true },
    { id: "oral-with-eye-contact", en: "Oral sex with eye contact", es: "Sexo oral con contacto visual", kind: 'mutual', counterpartScoped: true },
    { id: "oral-while-standing", en: "Oral sex while standing", es: "Sexo oral de pie", kind: 'mutual', counterpartScoped: true },
    { id: "oral-under-table", en: "Oral sex under a table or desk", es: "Sexo oral bajo una mesa o escritorio", kind: 'mutual', counterpartScoped: true },
    { id: "oral-wake-up", en: "Consensual wake-up oral sex", es: "Sexo oral consensuado para despertar", kind: 'mutual', counterpartScoped: true },
    { id: "receiving-oral-while-restrained", en: "Receiving oral while restrained", es: "Recibir sexo oral estando inmovilizado", kind: 'directed', counterpartScoped: true },
  ],
};
