import { CatalogueInsightTagDefinition, PracticeInsightSignals } from '../../../domain/catalogue/catalogue-insight';

export const CATALOGUE_REMAINING_INSIGHT_TAGS: readonly CatalogueInsightTagDefinition[] = [
  {
    id: 'pain-sensation',
    en: 'Pain-focused sensation',
    es: 'Sensación centrada en el dolor',
    descriptionEn: 'Experiences where controlled pain, impact, pinching, pressure or similarly sharp physical sensation is a meaningful part of the appeal.',
    descriptionEs: 'Experiencias donde el dolor controlado, impacto, pellizco, presión u otras sensaciones físicas agudas forman una parte significativa del atractivo.',
  },
  {
    id: 'transgression',
    en: 'Transgression',
    es: 'Transgresión',
    descriptionEn: 'Experiences whose appeal meaningfully involves crossing a social taboo, forbidden framing or deliberately provocative boundary in fantasy or consensual play.',
    descriptionEs: 'Experiencias cuyo atractivo implica de forma significativa cruzar un tabú social, un marco prohibido o un límite deliberadamente provocador dentro de la fantasía o el juego consensuado.',
  },
  {
    id: 'fantasy-imagination',
    en: 'Fantasy & imagination',
    es: 'Fantasía e imaginación',
    descriptionEn: 'Experiences where an imagined premise, impossible element or strongly fictional scenario matters independently from embodying a particular role.',
    descriptionEs: 'Experiencias donde una premisa imaginada, un elemento imposible o un escenario claramente ficticio importa independientemente de interpretar un rol concreto.',
  },
] as const;

export const CATALOGUE_V3_REMAINING_PRACTICE_INSIGHTS: readonly PracticeInsightSignals[] = [
  // Psychological play
  { practiceId: 'praise-kink', signals: { connection: 0.5, tenderness: 0.25, sensuality: 0.25 } },
  { practiceId: 'body-worship', signals: { 'service-orientation': 0.75, sensuality: 0.75, connection: 0.25 } },
  { practiceId: 'foot-worship', signals: { 'service-orientation': 0.75, sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'boot-worship', signals: { 'service-orientation': 0.75, 'aesthetic-presentation': 0.5, 'role-immersion': 0.25, exploration: 0.25 } },
  { practiceId: 'humiliation', signals: { 'power-exchange': 0.75, intensity: 0.5 } },
  { practiceId: 'degradation', signals: { 'power-exchange': 1, intensity: 0.75 } },
  { practiceId: 'embarrassment-play', signals: { 'power-exchange': 0.5, intensity: 0.5, playfulness: 0.25 } },
  { practiceId: 'exposure-humiliation', signals: { 'power-exchange': 0.75, visibility: 1, intensity: 0.5 } },
  { practiceId: 'small-penis-humiliation', signals: { 'power-exchange': 0.75, intensity: 0.5 } },
  { practiceId: 'breast-size-humiliation', signals: { 'power-exchange': 0.75, intensity: 0.5 } },
  { practiceId: 'orgasm-humiliation', signals: { 'power-exchange': 0.75, intensity: 0.5 } },
  { practiceId: 'objectification', signals: { 'power-exchange': 0.75, 'role-immersion': 0.5, intensity: 0.25 } },
  { practiceId: 'furniture-roleplay', signals: { 'power-exchange': 0.75, 'role-immersion': 1, 'service-orientation': 0.5, physicality: 0.25 } },
  { practiceId: 'begging', signals: { 'power-exchange': 0.75, 'role-immersion': 0.25, intensity: 0.25 } },
  { practiceId: 'teasing-verbal', signals: { playfulness: 0.75, sensuality: 0.25 } },
  { practiceId: 'dirty-talk', signals: { intensity: 0.5, playfulness: 0.25, sensuality: 0.25 } },
  { practiceId: 'name-calling', signals: { 'power-exchange': 0.5, intensity: 0.5, 'role-immersion': 0.25 } },
  { practiceId: 'mocking', signals: { 'power-exchange': 0.5, playfulness: 0.5, intensity: 0.25 } },
  { practiceId: 'anticipation', signals: { 'slow-pace': 0.5, intensity: 0.5, playfulness: 0.25 } },
  { practiceId: 'fear-play', signals: { intensity: 1, 'power-exchange': 0.5, exploration: 0.5 } },
  { practiceId: 'blackmail-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 1, intensity: 0.75, transgression: 0.5 } },
  { practiceId: 'mind-games', signals: { 'power-exchange': 0.75, intensity: 0.5, exploration: 0.5 } },

  // Sensation play
  { practiceId: 'spanking', signals: { 'pain-sensation': 0.5, intensity: 0.5, playfulness: 0.25 } },
  { practiceId: 'slapping-body', signals: { 'pain-sensation': 0.5, intensity: 0.5 } },
  { practiceId: 'face-slapping', signals: { 'pain-sensation': 0.75, intensity: 0.75, 'power-exchange': 0.25 } },
  { practiceId: 'paddling', signals: { 'pain-sensation': 0.75, intensity: 0.75, 'power-exchange': 0.25 } },
  { practiceId: 'flogging', signals: { 'pain-sensation': 0.75, intensity: 0.75, exploration: 0.25 } },
  { practiceId: 'whipping', signals: { 'pain-sensation': 1, intensity: 1, exploration: 0.5 } },
  { practiceId: 'caning', signals: { 'pain-sensation': 1, intensity: 1, exploration: 0.5 } },
  { practiceId: 'cropping', signals: { 'pain-sensation': 0.75, intensity: 0.75, exploration: 0.5 } },
  { practiceId: 'belting', signals: { 'pain-sensation': 0.75, intensity: 0.75, 'role-immersion': 0.25 } },
  { practiceId: 'wooden-spoon-impact', signals: { 'pain-sensation': 0.5, intensity: 0.5, playfulness: 0.25 } },
  { practiceId: 'rough-grabbing', signals: { intensity: 0.75, physicality: 0.5, 'pain-sensation': 0.25 } },
  { practiceId: 'biting', signals: { 'pain-sensation': 0.5, sensuality: 0.5, intensity: 0.5 } },
  { practiceId: 'scratching', signals: { 'pain-sensation': 0.5, sensuality: 0.5, intensity: 0.25 } },
  { practiceId: 'pinching', signals: { 'pain-sensation': 0.5, sensuality: 0.25 } },
  { practiceId: 'hair-pulling', signals: { 'pain-sensation': 0.5, 'power-exchange': 0.5, sensuality: 0.25 } },
  { practiceId: 'nipple-pinching', signals: { 'pain-sensation': 0.75, sensuality: 0.5 } },
  { practiceId: 'breast-slapping', signals: { 'pain-sensation': 0.75, intensity: 0.75 } },
  { practiceId: 'genital-slapping', signals: { 'pain-sensation': 1, intensity: 0.75 } },
  { practiceId: 'pressure-points', signals: { 'pain-sensation': 0.75, exploration: 0.5 } },
  { practiceId: 'clothespins', signals: { 'pain-sensation': 0.75, exploration: 0.5, playfulness: 0.25 } },
  { practiceId: 'nipple-clamp-sensation', signals: { 'pain-sensation': 0.75, sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'ice-play', signals: { sensuality: 0.5, exploration: 0.25, playfulness: 0.25 } },
  { practiceId: 'warm-wax', signals: { sensuality: 0.5, 'pain-sensation': 0.25, exploration: 0.5 } },
  { practiceId: 'temperature-contrast', signals: { sensuality: 0.75, exploration: 0.5 } },
  { practiceId: 'electrostimulation-mild', signals: { sensuality: 0.5, exploration: 0.75, intensity: 0.25 } },
  { practiceId: 'tickling', signals: { playfulness: 1, sensuality: 0.5, intensity: 0.25 } },
  { practiceId: 'feather-sensation', signals: { sensuality: 0.75, tenderness: 0.25, playfulness: 0.25 } },
  { practiceId: 'sensory-deprivation', signals: { 'sensory-restriction': 1, exploration: 0.75, intensity: 0.25 } },
  { practiceId: 'sensory-overload', signals: { intensity: 0.75, exploration: 0.75, sensuality: 0.5 } },

  // Fluids, substances & messy play
  { practiceId: 'spitting-on-body', signals: { exploration: 0.5, 'power-exchange': 0.25, transgression: 0.25 } },
  { practiceId: 'spitting-in-mouth', signals: { exploration: 0.75, 'power-exchange': 0.5, transgression: 0.5, intensity: 0.25 } },
  { practiceId: 'saliva-sharing', signals: { reciprocity: 0.75, sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'drooling', signals: { sensuality: 0.25, exploration: 0.5, transgression: 0.25 } },
  { practiceId: 'semen-on-face', signals: { visibility: 0.5, exploration: 0.5, 'power-exchange': 0.25 } },
  { practiceId: 'semen-on-breasts', signals: { visibility: 0.5, exploration: 0.5, sensuality: 0.25 } },
  { practiceId: 'semen-on-buttocks', signals: { visibility: 0.5, exploration: 0.5, sensuality: 0.25 } },
  { practiceId: 'semen-in-mouth', signals: { exploration: 0.5, sensuality: 0.25 } },
  { practiceId: 'swallowing', signals: { exploration: 0.5, sensuality: 0.25 } },
  { practiceId: 'spitting-semen', signals: { exploration: 0.5 } },
  { practiceId: 'snowballing', signals: { reciprocity: 0.75, exploration: 0.75, transgression: 0.25 } },
  { practiceId: 'creampie-vaginal', signals: { sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'creampie-anal', signals: { sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'creampie-cleanup', signals: { 'service-orientation': 0.5, sensuality: 0.25, exploration: 0.5 } },
  { practiceId: 'female-ejaculation', signals: { sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'squirting-on-partner', signals: { sensuality: 0.5, playfulness: 0.25, exploration: 0.5 } },
  { practiceId: 'urine-play', signals: { exploration: 1, transgression: 0.75, intensity: 0.5 } },
  { practiceId: 'urine-drinking', signals: { exploration: 1, transgression: 1, intensity: 0.75 } },
  { practiceId: 'blood-play', signals: { exploration: 0.75, transgression: 0.75, intensity: 0.75 } },
  { practiceId: 'blood-on-body', signals: { exploration: 0.75, transgression: 0.75, intensity: 0.5, visibility: 0.25 } },
  { practiceId: 'blood-drinking', signals: { exploration: 1, transgression: 1, intensity: 1 } },
  { practiceId: 'scat-on-body', signals: { exploration: 1, transgression: 1, intensity: 0.75 } },
  { practiceId: 'scat-in-mouth', signals: { exploration: 1, transgression: 1, intensity: 1 } },
  { practiceId: 'scat-ingestion', signals: { exploration: 1, transgression: 1, intensity: 1 } },
  { practiceId: 'sweat-play', signals: { sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'sweat-licking', signals: { sensuality: 0.75, exploration: 0.5 } },
  { practiceId: 'food-body-play', signals: { playfulness: 0.75, sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'oil-body-play', signals: { sensuality: 1, exploration: 0.25 } },
  { practiceId: 'mud-body-play', signals: { exploration: 0.75, playfulness: 0.5, sensuality: 0.25 } },

  // Taboo fantasies
  { practiceId: 'adult-taboo-fantasy', signals: { transgression: 1, 'fantasy-imagination': 0.75, exploration: 0.75 } },
  { practiceId: 'cheating-fantasy', signals: { transgression: 0.75, 'role-immersion': 0.5, 'fantasy-imagination': 0.5, intensity: 0.25 } },
  { practiceId: 'adult-ageplay-roleplay', signals: { transgression: 0.75, 'role-immersion': 1, 'fantasy-imagination': 0.5, exploration: 0.5 } },
  { practiceId: 'caregiver-little-adult-roleplay', signals: { transgression: 0.75, 'role-immersion': 1, 'power-exchange': 0.5, 'fantasy-imagination': 0.5 } },
  { practiceId: 'family-role-taboo-fantasy', signals: { transgression: 1, 'role-immersion': 1, 'fantasy-imagination': 0.75 } },
  { practiceId: 'religious-taboo-fantasy', signals: { transgression: 1, 'role-immersion': 0.75, 'aesthetic-presentation': 0.5, 'fantasy-imagination': 0.5 } },
  { practiceId: 'extremist-war-symbolism-fantasy', signals: { transgression: 1, 'role-immersion': 0.75, 'aesthetic-presentation': 1, 'fantasy-imagination': 0.5 } },
  { practiceId: 'consensual-non-consent-roleplay', signals: { transgression: 1, 'role-immersion': 0.75, 'power-exchange': 1, intensity: 1, 'fantasy-imagination': 0.5 } },
  { practiceId: 'free-use-unaware-roleplay', signals: { transgression: 1, 'role-immersion': 1, 'power-exchange': 1, intensity: 0.75, 'fantasy-imagination': 0.5 } },
  { practiceId: 'sleep-roleplay', signals: { transgression: 1, 'role-immersion': 1, 'power-exchange': 0.75, 'fantasy-imagination': 0.5 } },
  { practiceId: 'public-use-fantasy', signals: { transgression: 1, 'role-immersion': 1, 'power-exchange': 1, visibility: 0.75, 'group-social': 0.5, 'fantasy-imagination': 0.5 } },
  { practiceId: 'death-corpse-roleplay', signals: { transgression: 1, 'role-immersion': 1, 'fantasy-imagination': 1, intensity: 0.75 } },

  // Surrealism & impossible fantasies
  { practiceId: 'surreal-fantasy-roleplay', signals: { 'fantasy-imagination': 1, 'role-immersion': 0.75, exploration: 1 } },
  { practiceId: 'futanari-fantasy', signals: { 'fantasy-imagination': 1, exploration: 0.75, 'aesthetic-presentation': 0.5 } },
  { practiceId: 'transformation-fantasy', signals: { 'fantasy-imagination': 1, exploration: 1, 'role-immersion': 0.5, 'aesthetic-presentation': 0.5 } },
  { practiceId: 'size-change-fantasy', signals: { 'fantasy-imagination': 1, exploration: 1, intensity: 0.25 } },
  { practiceId: 'extra-anatomy-fantasy', signals: { 'fantasy-imagination': 1, exploration: 1, 'aesthetic-presentation': 0.5 } },
  { practiceId: 'tentacle-fantasy', signals: { 'fantasy-imagination': 1, exploration: 1, intensity: 0.5 } },
  { practiceId: 'furry-anthro-fantasy', signals: { 'fantasy-imagination': 1, 'role-immersion': 1, 'aesthetic-presentation': 0.75, exploration: 0.75 } },
  { practiceId: 'monster-roleplay', signals: { 'fantasy-imagination': 1, 'role-immersion': 1, intensity: 0.5, exploration: 0.75 } },
  { practiceId: 'alien-fantasy', signals: { 'fantasy-imagination': 1, 'role-immersion': 0.75, exploration: 1, intensity: 0.25 } },
  { practiceId: 'vore-fantasy', signals: { 'fantasy-imagination': 1, exploration: 1, intensity: 0.75, transgression: 0.25 } },

  // Edge & higher-intensity practices
  { practiceId: 'breath-play', signals: { intensity: 1, exploration: 0.75, 'power-exchange': 0.25 } },
  { practiceId: 'choking-fantasy', signals: { intensity: 1, 'power-exchange': 0.75, 'fantasy-imagination': 0.25, 'pain-sensation': 0.25 } },
  { practiceId: 'smothering', signals: { intensity: 1, 'power-exchange': 0.75, 'physical-restraint': 0.25 } },
  { practiceId: 'water-bondage-fantasy', signals: { 'fantasy-imagination': 0.5, intensity: 1, 'physical-restraint': 0.5, exploration: 1 } },
  { practiceId: 'needle-play', signals: { 'pain-sensation': 1, intensity: 1, exploration: 1 } },
  { practiceId: 'piercing-play', signals: { 'pain-sensation': 1, intensity: 1, exploration: 1, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'cutting-play', signals: { 'pain-sensation': 1, intensity: 1, exploration: 1, transgression: 0.25 } },
  { practiceId: 'scarification-fantasy', signals: { 'pain-sensation': 1, intensity: 1, exploration: 1, 'fantasy-imagination': 0.25, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'branding-fantasy', signals: { 'pain-sensation': 1, intensity: 1, exploration: 1, 'fantasy-imagination': 0.25 } },
  { practiceId: 'hot-wax-intense', signals: { 'pain-sensation': 0.75, intensity: 1, sensuality: 0.25, exploration: 0.75 } },
  { practiceId: 'fire-play', signals: { 'pain-sensation': 0.75, intensity: 1, exploration: 1 } },
  { practiceId: 'electrostimulation-intense', signals: { 'pain-sensation': 0.75, intensity: 1, exploration: 1 } },
  { practiceId: 'pussy-torture', signals: { 'pain-sensation': 1, intensity: 1, 'power-exchange': 0.75 } },
  { practiceId: 'cock-and-ball-torture', signals: { 'pain-sensation': 1, intensity: 1, 'power-exchange': 0.75 } },
  { practiceId: 'breast-torture', signals: { 'pain-sensation': 1, intensity: 1, 'power-exchange': 0.75 } },
  { practiceId: 'nipple-torture', signals: { 'pain-sensation': 1, intensity: 1, 'power-exchange': 0.75 } },
  { practiceId: 'suspension-bondage', signals: { 'physical-restraint': 1, physicality: 1, intensity: 0.75, exploration: 0.75 } },
  { practiceId: 'inversion-bondage', signals: { 'physical-restraint': 1, physicality: 1, intensity: 0.75, exploration: 1 } },
  { practiceId: 'predicament-bondage', signals: { 'physical-restraint': 1, physicality: 0.75, intensity: 0.75, 'power-exchange': 0.5, exploration: 0.75 } },
  { practiceId: 'long-duration-restraint', signals: { 'physical-restraint': 1, 'slow-pace': 1, intensity: 0.75, 'power-exchange': 0.5 } },
  { practiceId: 'vacuum-bed', signals: { 'physical-restraint': 1, 'sensory-restriction': 0.5, intensity: 0.75, exploration: 1 } },
  { practiceId: 'vacuum-cube', signals: { 'physical-restraint': 1, 'sensory-restriction': 0.5, intensity: 0.75, exploration: 1 } },
] as const;
