import { CatalogueInsightTagDefinition, PracticeInsightSignals } from '../../../domain/catalogue/catalogue-insight';

/**
 * Provisional semantic vocabulary for future orientative profile insights.
 *
 * Signals are intentionally reusable across category boundaries. They describe qualities of a
 * practice rather than questionnaire groups, while the eventual chart remains free to combine
 * several signals into user-facing metrics.
 */
export const CATALOGUE_INSIGHT_TAGS: readonly CatalogueInsightTagDefinition[] = [
  {
    id: 'connection',
    en: 'Emotional connection',
    es: 'Conexión emocional',
    descriptionEn: 'Practices where emotional closeness and mutual connection are central.',
    descriptionEs: 'Prácticas donde la cercanía emocional y la conexión mutua son centrales.',
  },
  {
    id: 'tenderness',
    en: 'Tenderness',
    es: 'Ternura',
    descriptionEn: 'Gentle, affectionate and caring physical interaction.',
    descriptionEs: 'Interacción física suave, afectuosa y cuidadosa.',
  },
  {
    id: 'romance',
    en: 'Romance',
    es: 'Romanticismo',
    descriptionEn: 'Romantic tone, gestures or emotional framing around intimacy.',
    descriptionEs: 'Tono, gestos o marco emocional romántico alrededor de la intimidad.',
  },
  {
    id: 'sensuality',
    en: 'Sensuality',
    es: 'Sensualidad',
    descriptionEn: 'Sensory, body-focused enjoyment that emphasises touch and atmosphere.',
    descriptionEs: 'Disfrute sensorial y corporal que enfatiza el tacto y el ambiente.',
  },
  {
    id: 'intensity',
    en: 'Intensity',
    es: 'Intensidad',
    descriptionEn: 'Practices characterised by energetic, forceful or highly charged interaction.',
    descriptionEs: 'Prácticas caracterizadas por una interacción enérgica, fuerte o muy cargada.',
  },
  {
    id: 'slow-pace',
    en: 'Slow pace',
    es: 'Ritmo lento',
    descriptionEn: 'Experiences where taking time and prolonging the interaction are meaningful.',
    descriptionEs: 'Experiencias donde tomarse tiempo y prolongar la interacción es significativo.',
  },
  {
    id: 'fast-pace',
    en: 'Fast pace',
    es: 'Ritmo rápido',
    descriptionEn: 'Brief, direct or deliberately fast-paced experiences.',
    descriptionEs: 'Experiencias breves, directas o deliberadamente rápidas.',
  },
  {
    id: 'spontaneity',
    en: 'Spontaneity',
    es: 'Espontaneidad',
    descriptionEn: 'Practices strongly associated with unplanned or in-the-moment intimacy.',
    descriptionEs: 'Prácticas muy asociadas con la intimidad no planificada o del momento.',
  },
  {
    id: 'playfulness',
    en: 'Playfulness',
    es: 'Juego',
    descriptionEn: 'Humour, teasing, lightness or playful interaction.',
    descriptionEs: 'Humor, provocación, ligereza o interacción juguetona.',
  },
  {
    id: 'exploration',
    en: 'Exploration',
    es: 'Exploración',
    descriptionEn: 'Novelty, experimentation or trying less familiar experiences.',
    descriptionEs: 'Novedad, experimentación o interés por experiencias menos familiares.',
  },
  {
    id: 'visibility',
    en: 'Visibility',
    es: 'Exposición',
    descriptionEn: 'Being seen, showing, watching or moving intimacy beyond a strictly private setting.',
    descriptionEs: 'Ser visto, mostrar, observar o llevar la intimidad más allá de un entorno estrictamente privado.',
  },
  {
    id: 'aesthetic-presentation',
    en: 'Aesthetic presentation',
    es: 'Presentación estética',
    descriptionEn: 'Visual styling, clothing, adornment or body presentation as a meaningful part of attraction.',
    descriptionEs: 'Estilismo visual, ropa, adornos o presentación corporal como parte significativa del atractivo.',
  },
  {
    id: 'role-immersion',
    en: 'Role immersion',
    es: 'Inmersión en rol',
    descriptionEn: 'Appearance, behaviour or framing used to embody a persona, archetype or imagined role.',
    descriptionEs: 'Apariencia, comportamiento o marco utilizados para encarnar una personalidad, arquetipo o rol imaginado.',
  },
  {
    id: 'reciprocity',
    en: 'Reciprocity',
    es: 'Reciprocidad',
    descriptionEn: 'Practices where reciprocal participation, coordinated giving and receiving or actively sharing the same interaction is central.',
    descriptionEs: 'Prácticas donde la participación recíproca, coordinar dar y recibir o compartir activamente la misma interacción es central.',
  },
  {
    id: 'physicality',
    en: 'Physicality',
    es: 'Fisicalidad',
    descriptionEn: 'Practices where strength, balance, flexibility or active body coordination are a meaningful part of the experience.',
    descriptionEs: 'Prácticas donde la fuerza, el equilibrio, la flexibilidad o la coordinación corporal activa forman una parte significativa de la experiencia.',
  },
  {
    id: 'power-exchange',
    en: 'Power exchange',
    es: 'Intercambio de poder',
    descriptionEn: 'Practices where control, authority, submission or negotiated power are meaningful.',
    descriptionEs: 'Prácticas donde el control, la autoridad, la sumisión o el poder negociado son significativos.',
  },
  {
    id: 'group-social',
    en: 'Group or social context',
    es: 'Contexto grupal o social',
    descriptionEn: 'Experiences involving multiple participants or a meaningful social component.',
    descriptionEs: 'Experiencias con varias personas o con un componente social significativo.',
  },
] as const;

/**
 * Semantic signals for every practice in the categories already migrated to the 0.2 taxonomy.
 * Strength describes the practice, not the user's preference for it; scoring remains a future layer.
 */
export const CATALOGUE_V3_PRACTICE_INSIGHTS: readonly PracticeInsightSignals[] = [
  // Affection & intimacy
  { practiceId: 'kissing', signals: { connection: 0.75, tenderness: 0.5, sensuality: 0.5, romance: 0.25 } },
  { practiceId: 'making-out', signals: { connection: 0.5, sensuality: 0.75, intensity: 0.5 } },
  { practiceId: 'verbal-affection', signals: { connection: 1, tenderness: 0.75, romance: 0.5 } },
  { practiceId: 'holding-hands', signals: { connection: 0.75, tenderness: 0.75, romance: 0.5 } },
  { practiceId: 'hair-stroking', signals: { connection: 0.75, tenderness: 1, sensuality: 0.25 } },
  { practiceId: 'face-caressing', signals: { connection: 0.75, tenderness: 1, sensuality: 0.5 } },
  { practiceId: 'back-rubs', signals: { connection: 0.5, tenderness: 0.75, sensuality: 0.5 } },
  { practiceId: 'skin-to-skin-contact', signals: { connection: 0.75, tenderness: 0.5, sensuality: 0.75 } },
  { practiceId: 'cuddling', signals: { connection: 1, tenderness: 1, sensuality: 0.25, 'slow-pace': 0.5 } },
  { practiceId: 'spooning', signals: { connection: 1, tenderness: 1, sensuality: 0.25, 'slow-pace': 0.5 } },
  { practiceId: 'sleeping-naked-together', signals: { connection: 0.75, tenderness: 0.5, sensuality: 0.5, 'slow-pace': 0.5 } },
  { practiceId: 'showering-together', signals: { connection: 0.5, tenderness: 0.25, sensuality: 0.75 } },
  { practiceId: 'bathing-together', signals: { connection: 0.75, tenderness: 0.5, sensuality: 0.75, 'slow-pace': 0.5 } },
  { practiceId: 'sensual-massage', signals: { connection: 0.5, tenderness: 0.5, sensuality: 1, 'slow-pace': 0.5 } },

  // Sexual style, rhythm & atmosphere
  { practiceId: 'romantic-sex', signals: { connection: 1, romance: 1, tenderness: 0.5, sensuality: 0.5 } },
  { practiceId: 'passionate-sex', signals: { connection: 0.25, sensuality: 0.5, intensity: 1 } },
  { practiceId: 'playful-sex', signals: { playfulness: 1, spontaneity: 0.5, connection: 0.25 } },
  { practiceId: 'competitive-sex', signals: { playfulness: 0.5, intensity: 0.75, exploration: 0.25 } },
  { practiceId: 'eye-contact', signals: { connection: 1, sensuality: 0.5, intensity: 0.25 } },
  { practiceId: 'slow-sex', signals: { connection: 0.5, sensuality: 0.75, 'slow-pace': 1 } },
  { practiceId: 'quickies', signals: { 'fast-pace': 1, spontaneity: 1, intensity: 0.25 } },
  { practiceId: 'extended-foreplay', signals: { sensuality: 0.75, 'slow-pace': 1, connection: 0.25 } },
  { practiceId: 'morning-sex', signals: { sensuality: 0.25, spontaneity: 0.5 } },
  { practiceId: 'sleepy-sex', signals: { connection: 0.25, tenderness: 0.25, 'slow-pace': 0.75, spontaneity: 0.25 } },

  // Clothing, appearance & lingerie
  { practiceId: 'clothed-sex', signals: { 'aesthetic-presentation': 0.5 } },
  { practiceId: 'partial-nudity', signals: { 'aesthetic-presentation': 0.5, visibility: 0.5, sensuality: 0.5 } },
  { practiceId: 'full-nudity', signals: { visibility: 0.75, sensuality: 0.5 } },
  { practiceId: 'lingerie', signals: { 'aesthetic-presentation': 1, sensuality: 0.75, romance: 0.25 } },
  { practiceId: 'stockings', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.5 } },
  { practiceId: 'thigh-highs', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.5 } },
  { practiceId: 'garter-belts', signals: { 'aesthetic-presentation': 1, sensuality: 0.75 } },
  { practiceId: 'corsets', signals: { 'aesthetic-presentation': 1, sensuality: 0.5 } },
  { practiceId: 'bodysuits', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.5 } },
  { practiceId: 'lace-clothing', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.75, romance: 0.25 } },
  { practiceId: 'silk-satin', signals: { 'aesthetic-presentation': 0.5, sensuality: 1, tenderness: 0.25 } },
  { practiceId: 'high-heels', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.25 } },
  { practiceId: 'boots', signals: { 'aesthetic-presentation': 0.75 } },
  { practiceId: 'leather-clothing', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.5, intensity: 0.25 } },
  { practiceId: 'latex-clothing', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.75, exploration: 0.5 } },
  { practiceId: 'pvc-clothing', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'harnesses-fashion', signals: { 'aesthetic-presentation': 1, sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'chokers', signals: { 'aesthetic-presentation': 0.75 } },
  { practiceId: 'collars-fashion', signals: { 'aesthetic-presentation': 0.75 } },
  { practiceId: 'masks', signals: { 'aesthetic-presentation': 0.75, 'role-immersion': 0.5, exploration: 0.25 } },
  { practiceId: 'gloves', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.25 } },
  { practiceId: 'suits', signals: { 'aesthetic-presentation': 0.75, 'role-immersion': 0.25 } },
  { practiceId: 'uniforms', signals: { 'aesthetic-presentation': 0.75, 'role-immersion': 0.75, playfulness: 0.25 } },
  { practiceId: 'sportswear', signals: { 'aesthetic-presentation': 0.5 } },
  { practiceId: 'cosplay', signals: { 'aesthetic-presentation': 1, 'role-immersion': 1, playfulness: 0.75, exploration: 0.5 } },
  { practiceId: 'cross-dressing', signals: { 'aesthetic-presentation': 0.75, 'role-immersion': 0.25, exploration: 0.75 } },
  { practiceId: 'body-paint', signals: { 'aesthetic-presentation': 1, visibility: 0.75, exploration: 0.75, playfulness: 0.25, sensuality: 0.5 } },

  // Manual stimulation & masturbation
  { practiceId: 'solo-masturbation', signals: { sensuality: 0.5 } },
  { practiceId: 'hands-free-masturbation', signals: { sensuality: 0.5, exploration: 0.75 } },
  { practiceId: 'masturbating-together', signals: { reciprocity: 1, connection: 0.5, visibility: 0.5, sensuality: 0.5 } },
  { practiceId: 'watch-partner-masturbate', signals: { visibility: 1, sensuality: 0.5, connection: 0.25 } },
  { practiceId: 'guided-touch', signals: { reciprocity: 0.75, connection: 0.5, sensuality: 0.75 } },
  { practiceId: 'touching-over-clothes', signals: { sensuality: 0.5, playfulness: 0.25 } },
  { practiceId: 'touching-under-clothes', signals: { sensuality: 0.75, playfulness: 0.25 } },
  { practiceId: 'mutual-handjobs', signals: { reciprocity: 1, sensuality: 0.75, connection: 0.25 } },
  { practiceId: 'handjob', signals: { sensuality: 0.5 } },
  { practiceId: 'vulva-hand-stimulation', signals: { sensuality: 0.5 } },
  { practiceId: 'clitoral-stimulation', signals: { sensuality: 0.75 } },
  { practiceId: 'fingering-vaginal', signals: { sensuality: 0.75 } },
  { practiceId: 'fingering-anal', signals: { sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'breast-stimulation-by-hand', signals: { sensuality: 0.75 } },
  { practiceId: 'nipple-stimulation-by-hand', signals: { sensuality: 0.75 } },
  { practiceId: 'perineum-massage', signals: { sensuality: 0.75, 'slow-pace': 0.25 } },
  { practiceId: 'prostate-massage-manual', signals: { sensuality: 0.75, exploration: 0.25 } },

  // Oral sex
  { practiceId: 'cunnilingus', signals: { sensuality: 0.75, connection: 0.25 } },
  { practiceId: 'fellatio', signals: { sensuality: 0.75, connection: 0.25 } },
  { practiceId: 'deep-throat', signals: { sensuality: 0.5, intensity: 0.75, exploration: 0.25 } },
  { practiceId: 'oral-teasing', signals: { sensuality: 0.75, playfulness: 0.5, 'slow-pace': 0.25 } },
  { practiceId: 'oral-anal', signals: { sensuality: 0.5, exploration: 0.75 } },
  { practiceId: 'oral-nipples', signals: { sensuality: 0.75, tenderness: 0.25 } },
  { practiceId: 'oral-breasts', signals: { sensuality: 0.75, tenderness: 0.25 } },
  { practiceId: 'oral-fingers', signals: { sensuality: 0.5, playfulness: 0.25 } },
  { practiceId: 'oral-toes', signals: { sensuality: 0.5, exploration: 0.5 } },

  // Penetration
  { practiceId: 'vaginal-penetration', signals: { sensuality: 0.75 } },
  { practiceId: 'anal-penetration', signals: { sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'prostate-penetration', signals: { sensuality: 0.75, exploration: 0.25 } },
  { practiceId: 'cervix-contact', signals: { sensuality: 0.5, intensity: 0.5, exploration: 0.25 } },
  { practiceId: 'shallow-penetration', signals: { sensuality: 0.5 } },
  { practiceId: 'deep-penetration', signals: { sensuality: 0.5, intensity: 0.5 } },
  { practiceId: 'slow-penetration', signals: { sensuality: 0.75, 'slow-pace': 1 } },
  { practiceId: 'rough-penetration', signals: { intensity: 1, sensuality: 0.25 } },
  { practiceId: 'double-vaginal-penetration', signals: { intensity: 0.75, exploration: 0.75 } },
  { practiceId: 'double-anal-penetration', signals: { intensity: 1, exploration: 0.75 } },
  { practiceId: 'fisting-vaginal', signals: { intensity: 0.75, exploration: 1, 'slow-pace': 0.25 } },
  { practiceId: 'fisting-anal', signals: { intensity: 1, exploration: 1, 'slow-pace': 0.25 } },
  { practiceId: 'simultaneous-vaginal-anal-penetration', signals: { intensity: 0.75, exploration: 0.75 } },
  { practiceId: 'simultaneous-vaginal-oral-penetration', signals: { intensity: 0.75, exploration: 0.75 } },
  { practiceId: 'simultaneous-anal-oral-penetration', signals: { intensity: 0.75, exploration: 0.75 } },
  { practiceId: 'simultaneous-vaginal-anal-oral-penetration', signals: { intensity: 1, exploration: 1 } },

  // Sexual positions
  { practiceId: 'missionary', signals: { connection: 0.5, sensuality: 0.5 } },
  { practiceId: 'side-by-side-face-to-face', signals: { connection: 0.75, tenderness: 0.25, sensuality: 0.5, 'slow-pace': 0.25 } },
  { practiceId: 'kneeling-face-to-face', signals: { connection: 0.75, sensuality: 0.75, physicality: 0.5 } },
  { practiceId: 'seated-penetration', signals: { connection: 0.5, sensuality: 0.5, physicality: 0.25 } },
  { practiceId: 'lotus-position', signals: { connection: 0.75, sensuality: 0.75, 'slow-pace': 0.25, physicality: 0.25 } },
  { practiceId: 'cowgirl', signals: { sensuality: 0.5, physicality: 0.25 } },
  { practiceId: 'reverse-cowgirl', signals: { sensuality: 0.5, exploration: 0.25, physicality: 0.25 } },
  { practiceId: 'doggy-style', signals: { sensuality: 0.25, intensity: 0.5, physicality: 0.25 } },
  { practiceId: 'prone-rear-entry', signals: { sensuality: 0.5, intensity: 0.25 } },
  { practiceId: 'spooning-penetration', signals: { connection: 0.5, tenderness: 0.25, sensuality: 0.5, 'slow-pace': 0.25 } },
  { practiceId: 'legs-on-shoulders', signals: { intensity: 0.5, exploration: 0.25, physicality: 0.25 } },
  { practiceId: 'butterfly-position', signals: { sensuality: 0.5, exploration: 0.25, physicality: 0.25 } },
  { practiceId: 't-position', signals: { sensuality: 0.5, exploration: 0.5, physicality: 0.25 } },
  { practiceId: 'standing-penetration', signals: { physicality: 0.75, intensity: 0.25, exploration: 0.25 } },
  { practiceId: 'against-wall', signals: { physicality: 0.5, intensity: 0.5 } },
  { practiceId: 'standing-carry', signals: { physicality: 1, intensity: 0.5, exploration: 0.5, connection: 0.25 } },
  { practiceId: 'wheelbarrow-position', signals: { physicality: 1, intensity: 0.75, exploration: 0.75 } },
  { practiceId: 'bridge-position', signals: { physicality: 1, intensity: 0.5, exploration: 0.75 } },
  { practiceId: 'sixty-nine', signals: { reciprocity: 1, sensuality: 0.75, physicality: 0.25 } },
  { practiceId: 'face-sitting', signals: { sensuality: 0.5, intensity: 0.25, exploration: 0.5 } },

  // Toys
  { practiceId: 'vibrator', signals: { sensuality: 0.75, exploration: 0.25 } },
  { practiceId: 'wand-vibrator', signals: { sensuality: 0.75, intensity: 0.5 } },
  { practiceId: 'bullet-vibrator', signals: { sensuality: 0.75 } },
  { practiceId: 'rabbit-vibrator', signals: { sensuality: 0.75, exploration: 0.25 } },
  { practiceId: 'wearable-vibrator', signals: { sensuality: 0.75, exploration: 0.5, playfulness: 0.25 } },
  { practiceId: 'remote-control-toy', signals: { exploration: 0.5, playfulness: 0.5, 'power-exchange': 0.25 } },
  { practiceId: 'dildo', signals: { sensuality: 0.5 } },
  { practiceId: 'special-material-dildo', signals: { sensuality: 0.75, exploration: 0.5 } },
  { practiceId: 'fantasy-shaped-dildo', signals: { exploration: 1, playfulness: 0.25 } },
  { practiceId: 'double-ended-dildo', signals: { exploration: 0.5, reciprocity: 0.5, physicality: 0.25 } },
  { practiceId: 'vacuum-cup-toys', signals: { sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'anal-plug', signals: { sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'vibrating-anal-plug', signals: { sensuality: 0.5, exploration: 0.5, intensity: 0.25 } },
  { practiceId: 'anal-beads', signals: { sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'prostate-massager', signals: { sensuality: 0.75, exploration: 0.25 } },
  { practiceId: 'butt-plug-tail', signals: { exploration: 0.5, 'aesthetic-presentation': 0.5, 'role-immersion': 0.5 } },
  { practiceId: 'strap-on', signals: { sensuality: 0.5, exploration: 0.5, physicality: 0.25 } },
  { practiceId: 'strapless-strap-on', signals: { sensuality: 0.5, exploration: 0.5, reciprocity: 0.5, physicality: 0.25 } },
  { practiceId: 'penis-sleeve', signals: { sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'cock-ring', signals: { sensuality: 0.25 } },
  { practiceId: 'vibrating-cock-ring', signals: { sensuality: 0.5, reciprocity: 0.5 } },
  { practiceId: 'masturbator-sleeve', signals: { sensuality: 0.5 } },
  { practiceId: 'automatic-masturbator', signals: { sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'penis-pump', signals: { exploration: 0.5, intensity: 0.25 } },
  { practiceId: 'clitoral-suction-toy', signals: { sensuality: 0.75, exploration: 0.25, intensity: 0.25 } },
  { practiceId: 'kegel-balls', signals: { sensuality: 0.25, exploration: 0.25, physicality: 0.25 } },
  { practiceId: 'nipple-suction-cups', signals: { sensuality: 0.5, exploration: 0.5, intensity: 0.25 } },
  { practiceId: 'pinwheel', signals: { sensuality: 0.5, exploration: 0.5, playfulness: 0.25 } },
  { practiceId: 'sex-machine', signals: { exploration: 1, intensity: 0.75 } },
  { practiceId: 'sex-swing', signals: { exploration: 0.75, physicality: 0.75, playfulness: 0.25 } },
  { practiceId: 'positioning-pillow', signals: { exploration: 0.25, physicality: 0.25, sensuality: 0.25 } },

  // Orgasm control
  { practiceId: 'edging', signals: { 'slow-pace': 0.75, intensity: 0.25, playfulness: 0.25 } },
  { practiceId: 'orgasm-denial', signals: { 'power-exchange': 0.75, 'slow-pace': 0.5, intensity: 0.25 } },
  { practiceId: 'orgasm-control', signals: { 'power-exchange': 0.75, 'slow-pace': 0.25 } },
  { practiceId: 'no-orgasm-sex', signals: { exploration: 0.5, 'slow-pace': 0.25 } },
  { practiceId: 'ruined-orgasm', signals: { 'power-exchange': 0.75, intensity: 0.5, exploration: 0.5 } },
  { practiceId: 'forced-orgasm', signals: { 'power-exchange': 1, intensity: 0.75, exploration: 0.25 } },
  { practiceId: 'post-orgasm-stimulation', signals: { intensity: 0.75, exploration: 0.25, sensuality: 0.25 } },
  { practiceId: 'overstimulation', signals: { intensity: 1, exploration: 0.5 } },
  { practiceId: 'multiple-orgasms', signals: { intensity: 0.5, exploration: 0.25, sensuality: 0.5 } },
  { practiceId: 'simultaneous-orgasm', signals: { reciprocity: 1, connection: 0.5, sensuality: 0.5 } },
  { practiceId: 'hands-free-orgasm', signals: { exploration: 1, sensuality: 0.5 } },

  // Body focus & fetishes
  { practiceId: 'lips', signals: { sensuality: 0.75, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'tongue', signals: { sensuality: 0.75 } },
  { practiceId: 'hair', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.25 } },
  { practiceId: 'hair-length-short', signals: { 'aesthetic-presentation': 0.75 } },
  { practiceId: 'hair-length-medium', signals: { 'aesthetic-presentation': 0.75 } },
  { practiceId: 'hair-length-long', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.25 } },
  { practiceId: 'shaved-bald-head', signals: { 'aesthetic-presentation': 0.75, exploration: 0.25 } },
  { practiceId: 'facial-hair', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.25 } },
  { practiceId: 'ears', signals: { sensuality: 0.5 } },
  { practiceId: 'neck', signals: { sensuality: 0.75 } },
  { practiceId: 'chest-general', signals: { sensuality: 0.5, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'breast-size-small', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'breast-size-average', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'breast-size-large', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'nipples', signals: { sensuality: 0.75 } },
  { practiceId: 'muscles', signals: { 'aesthetic-presentation': 0.75, physicality: 0.25 } },
  { practiceId: 'slim-build', signals: { 'aesthetic-presentation': 0.75 } },
  { practiceId: 'curvy-build', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.25 } },
  { practiceId: 'stocky-build', signals: { 'aesthetic-presentation': 0.75, physicality: 0.25 } },
  { practiceId: 'stature-short', signals: { 'aesthetic-presentation': 0.5 } },
  { practiceId: 'stature-average', signals: { 'aesthetic-presentation': 0.5 } },
  { practiceId: 'stature-tall', signals: { 'aesthetic-presentation': 0.5 } },
  { practiceId: 'hands', signals: { sensuality: 0.5, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'fingers', signals: { sensuality: 0.5 } },
  { practiceId: 'bellies', signals: { sensuality: 0.5, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'navel', signals: { sensuality: 0.5, exploration: 0.25 } },
  { practiceId: 'buttocks', signals: { sensuality: 0.75, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'buttocks-size-small', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'buttocks-size-average', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'buttocks-size-large', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'legs', signals: { sensuality: 0.5, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'thighs', signals: { sensuality: 0.75 } },
  { practiceId: 'feet', signals: { sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'toes', signals: { sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'penis', signals: { sensuality: 0.75 } },
  { practiceId: 'penis-size-small', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'penis-size-average', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'penis-size-large', signals: { 'aesthetic-presentation': 0.5, sensuality: 0.5 } },
  { practiceId: 'testicles', signals: { sensuality: 0.75 } },
  { practiceId: 'vulva', signals: { sensuality: 0.75 } },
  { practiceId: 'pubic-hair', signals: { sensuality: 0.5, 'aesthetic-presentation': 0.5 } },
  { practiceId: 'body-hair', signals: { sensuality: 0.25, 'aesthetic-presentation': 0.5 } },
  { practiceId: 'armpits', signals: { sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'body-scent', signals: { sensuality: 0.75, exploration: 0.5 } },
  { practiceId: 'sweat', signals: { sensuality: 0.5, exploration: 0.75, intensity: 0.25 } },
  { practiceId: 'underwear', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.5 } },
  { practiceId: 'worn-underwear', signals: { sensuality: 0.5, exploration: 0.75, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'tattoos', signals: { 'aesthetic-presentation': 1, exploration: 0.25 } },
  { practiceId: 'piercings', signals: { 'aesthetic-presentation': 0.75, exploration: 0.5 } },
  { practiceId: 'facial-piercings', signals: { 'aesthetic-presentation': 1, exploration: 0.5 } },
  { practiceId: 'body-piercings', signals: { 'aesthetic-presentation': 0.75, exploration: 0.5 } },
  { practiceId: 'nipple-piercings', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.5, exploration: 0.5 } },
  { practiceId: 'genital-piercings', signals: { 'aesthetic-presentation': 0.75, sensuality: 0.5, exploration: 0.75 } },

  // Partners, groups & composition
  { practiceId: 'couple-plus-guest', signals: { 'group-social': 1, exploration: 0.75, reciprocity: 0.5 } },
  { practiceId: 'threesome-mmf', signals: { 'group-social': 1, exploration: 0.75, reciprocity: 0.5 } },
  { practiceId: 'threesome-mff', signals: { 'group-social': 1, exploration: 0.75, reciprocity: 0.5 } },
  { practiceId: 'threesome-mmm', signals: { 'group-social': 1, exploration: 0.75, reciprocity: 0.5 } },
  { practiceId: 'threesome-fff', signals: { 'group-social': 1, exploration: 0.75, reciprocity: 0.5 } },
  { practiceId: 'foursome', signals: { 'group-social': 1, exploration: 0.75, reciprocity: 0.75 } },
  { practiceId: 'group-sex', signals: { 'group-social': 1, exploration: 0.75, intensity: 0.5, reciprocity: 0.5 } },
  { practiceId: 'gangbang', signals: { 'group-social': 1, exploration: 0.75, intensity: 1 } },
  { practiceId: 'anonymous-group-scene', signals: { 'group-social': 1, exploration: 1, visibility: 0.25 } },
  { practiceId: 'swinging', signals: { 'group-social': 1, exploration: 0.75, reciprocity: 0.75 } },
  { practiceId: 'soft-swap', signals: { 'group-social': 0.75, exploration: 0.5, reciprocity: 0.75 } },
  { practiceId: 'full-swap', signals: { 'group-social': 1, exploration: 0.75, reciprocity: 0.75 } },
  { practiceId: 'same-room-sex', signals: { 'group-social': 0.75, visibility: 0.75, reciprocity: 0.5 } },
  { practiceId: 'watching-partner-with-other', signals: { 'group-social': 0.5, visibility: 1, exploration: 0.5 } },
  { practiceId: 'hotwife-dynamic', signals: { 'group-social': 0.75, exploration: 0.75, visibility: 0.5 } },
  { practiceId: 'cuckold-dynamic', signals: { 'group-social': 0.75, exploration: 0.75, visibility: 0.75 } },
  { practiceId: 'cuckquean-dynamic', signals: { 'group-social': 0.75, exploration: 0.75, visibility: 0.75 } },

  // Scenarios & roleplay
  { practiceId: 'roleplay-general', signals: { 'role-immersion': 1, exploration: 0.5, playfulness: 0.5 } },
  { practiceId: 'strangers-roleplay', signals: { 'role-immersion': 0.75, spontaneity: 0.5, exploration: 0.25, playfulness: 0.25 } },
  { practiceId: 'first-date-roleplay', signals: { 'role-immersion': 0.75, romance: 0.5, playfulness: 0.25 } },
  { practiceId: 'massage-roleplay', signals: { 'role-immersion': 0.5, sensuality: 0.75, 'slow-pace': 0.25 } },
  { practiceId: 'delivery-person-roleplay', signals: { 'role-immersion': 0.75, playfulness: 0.5, spontaneity: 0.25 } },
  { practiceId: 'hotel-roleplay', signals: { 'role-immersion': 0.5, exploration: 0.25, spontaneity: 0.25 } },
  { practiceId: 'office-roleplay', signals: { 'role-immersion': 0.75, 'aesthetic-presentation': 0.25, exploration: 0.25 } },
  { practiceId: 'boss-employee-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 0.75, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'teacher-student-adult-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 0.5, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'medical-professional-patient-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 0.5, exploration: 0.5, 'aesthetic-presentation': 0.25 } },
  { practiceId: 'doctor-nurse-roleplay', signals: { 'role-immersion': 1, 'aesthetic-presentation': 0.5, playfulness: 0.25 } },
  { practiceId: 'police-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 0.75, 'aesthetic-presentation': 0.5 } },
  { practiceId: 'royalty-servant-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 0.75, 'aesthetic-presentation': 0.75 } },
  { practiceId: 'celebrity-fan-roleplay', signals: { 'role-immersion': 1, 'aesthetic-presentation': 0.5, exploration: 0.25 } },
  { practiceId: 'prisoner-guard-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 1, intensity: 0.5 } },
  { practiceId: 'captor-captive-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 1, intensity: 0.75, exploration: 0.5 } },
  { practiceId: 'kidnapping-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 1, intensity: 0.75, exploration: 0.5 } },
  { practiceId: 'interrogation-roleplay', signals: { 'role-immersion': 1, 'power-exchange': 1, intensity: 0.75 } },
  { practiceId: 'fantasy-character-roleplay', signals: { 'role-immersion': 1, 'aesthetic-presentation': 0.75, exploration: 0.75, playfulness: 0.25 } },
  { practiceId: 'superhero-roleplay', signals: { 'role-immersion': 1, 'aesthetic-presentation': 0.75, playfulness: 0.5, exploration: 0.5 } },
  { practiceId: 'vampire-roleplay', signals: { 'role-immersion': 1, 'aesthetic-presentation': 0.75, sensuality: 0.5, intensity: 0.25 } },
  { practiceId: 'ritual-roleplay', signals: { 'role-immersion': 1, 'aesthetic-presentation': 0.75, exploration: 0.75, intensity: 0.25 } },
  { practiceId: 'pet-play-soft', signals: { 'role-immersion': 1, playfulness: 0.75, tenderness: 0.25, 'aesthetic-presentation': 0.5, 'power-exchange': 0.25 } },
  { practiceId: 'pet-play-intense', signals: { 'role-immersion': 1, 'power-exchange': 0.75, exploration: 0.5, physicality: 0.5, 'aesthetic-presentation': 0.5 } },
  { practiceId: 'primal-play', signals: { 'role-immersion': 0.75, physicality: 0.75, intensity: 0.75, exploration: 0.5, spontaneity: 0.25 } },
] as const;
